### ISSUE TITLE
Email delivery error

### ISSUE THREAD

**Issue by yuiopt** [bitnami/bitnami-docker-redmine#100]
When I use the redmine forget password function: the console shows: Email delivery error: 501 mail from address must be same as authorization user,   I use the same smtp config to send email by python smtplib,  it works fine.

**Comment by javsalgar** [comment]
Hi,

I am unable to reproduce the issue. I tried with my gmail credentials and found no issue at all.

<img width="757" alt="screen shot 2018-03-28 at 11 10 47" src="https://user-images.githubusercontent.com/1133777/38019958-51774886-3279-11e8-9307-f1512c619388.png">

I used port 587, in case it helps. Are you using a custom SMTP server?

**Comment by yuiopt** [comment]
@javsalgar yes, I have solved this, login as admin first and config the sender email address just the same as SMTP_USER in the docker-compose.yml

**Comment by javsalgar** [comment]
Hi,

Good to know that you solved the issue! However, I didn't need to do that. Maybe it has to do with your SMTP provider.

**Comment by yuiopt** [comment]
@javsalgar  Hi, I met another problem, The smtp provider treat some of the emails sending by redmine system as  spams,   for example , the issues email . And I have to change another smtp provider,  I did this but It does not work , It seems that the redmine service use a local driver as volumes to storage data,  the problem is that how can I migrate the redmine_redmine_data volume and change the email.

**Comment by javsalgar** [comment]
Have you tried entering the container with docker exec and modify the configuration files?
