### ISSUE TITLE
question: how to install plugin

### ISSUE THREAD

**Issue by EthenQ** [bitnami/bitnami-docker-redmine#101]

**Comment by carrodher** [comment]
Before installing a plugin, make sure that the plugin is compatible with your Redmine version. For plugins from the [Redmine Plugin Directory](http://www.redmine.org/plugins). Select your Redmine version and check if the plugin is compatible or not with your version using the drop down menu located in the top right margin: "Show only plugins compatible with Redmine: version".

1.  Get the .zip file or clone the git repository in the `/opt/bitnami/redmine/plugins` directory:
```
cd /opt/bitnami/redmine/plugins
```
If you have obtained a `.zip` file, Once you have the plugin `.zip` file, uncompress it an remove the `.zip` file. (Remember to replace _PLUGIN_NAME-x-y-z_ with the correct name and version of the plugin):
```
unzip PLUGIN_NAME-x-y-z.zip
rm PLUGIN_NAME-x-y-z.zip
```

IMPORTANT: Before installing the plugin, check the installation notes indicated in the plugin description or readme. Some plugins need special installation requirements.

2. Install the plugin:
```
cd /opt/bitnami/redmine/
bundle install
bundle exec rake redmine:plugins NAME=PLUGIN_NAME RAILS_ENV=production
```

> NOTE: It could display a warning message about the log production file. In that case, run the following commands:
> ```
> sudo chown :bitnami log/production.log
> sudo chmod g+w log/production.log
> ```

3. Restart services if needed, persisted folders are:
```
/opt/bitnami/redmine/conf
/opt/bitnami/redmine/public/plugin_assets
/opt/bitnami/redmine/plugins
/opt/bitnami/redmine/files
``` 

### Troubleshooting Plugin Installation
If you receive an error like this in Redmine 2.4.0-0 and newer:
```
You are trying to install in deployment mode after changing your Gemfile. Run 'bundle install' elsewhere and add the updated Gemfile.lock to version control.
```
Try adding the `--no-deployment` argument to the bundle install command as suggested in the error message.

**Comment by ephisr** [comment]
@tompizmor  thanks :)

![image](https://user-images.githubusercontent.com/26577860/41265594-dc24cde6-6da7-11e8-819f-6eb8d9ab413b.png)

**Comment by carrodher** [comment]
We are glad that you were able to fix the issue. I will close the issue, please reopen it if needed.

**Comment by marco-olimpio** [comment]
It also solved my issue :+1:

**Comment by zx1986** [comment]
so, I have to build my own docker image base on Bitnami's?

**Comment by juan131** [comment]
Hi @zx1986 

At this very moment we don't support a way to install custom plugins during the initialisation, therefore, I'm afraid that you'll have to build your own docker image based on Bitnami one.
