### ISSUE TITLE
Run IMAP Mail Receive as Cron

### ISSUE THREAD

**Issue by mathewlsm** [bitnami/bitnami-docker-redmine#104]
Hello,

we have installed bitnami/redmine docker image and want to receive EMail from an IMAP-Server.

I can run and receive manually the mail with "rake redmine:email:receive_imap RAILS_ENV="production" host=..." command. But how can we shedule this command with cron in these distribution. I think crontab isn't installed yet? 

bitnami/redmine                  latest              6c1c914e28db        2 months ago        723 MB
bitnami/mariadb                  latest              610f954177c4        2 months ago        286 MB

Thank you.

**Comment by marcosbc** [comment]
Hi,

You can install cron with the following command inside the container:

    $ install_packages cron

If you need to have a Docker image with this package, you can create the following `Dockerfile`:

    FROM bitnami/redmine:latest
    RUN install_packages cron

And then build a new Docker image, e.g. with the following command:

    $ docker build -t myredmine .

You can use this image with Docker Compose by editing the `docker-compose.yml` file and changing the line below:

        image: 'bitnami/mariadb:latest'

To this:

        image: 'myredmine'
