### ISSUE TITLE
docker-compose example does not work for me right now

### ISSUE THREAD

**Issue by stefangweichinger** [bitnami/bitnami-docker-redmine#107]
**Description**

plain example docker-compose.yml does not bring up working container(s)

**Steps to reproduce the issue:**

1. take your 1st docker-compose.yml from https://hub.docker.com/r/bitnami/redmine/

2. docker-compose up

3. after 1st errors : stop/start/remove/recreate containers, docker-compose down -v, etc etc

**Describe the results you received:**

mariadb_1  | 2018-12-27  6:37:15 140216602257280 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1  | 2018-12-27  6:37:15 140216602257280 [Warning] 'proxies_priv' entry '@% root@e24a48475310' ignored in --skip-name-resolve mode.
mariadb_1  | 2018-12-27  6:37:15 140216602257280 [Note] /opt/bitnami/mariadb/sbin/mysqld: ready for connections.
mariadb_1  | Version: '10.1.37-MariaDB'  socket: '/opt/bitnami/mariadb/tmp/mysql.sock'  port: 3306  Source distribution
redmine_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
redmine_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
redmine_1  | redmine INFO  Preparing Redmine environment...
redmine_1  | redmine INFO  Generating new secret...
redmine_1  | redmine INFO  Migrating database...
redmine_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redmine'
redmine_redmine_1 exited with code 1

**Describe the results you expected:**

working redmine installation at http://localhost

**Version**

- Output of `docker version`:

```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-62.git9cb56fd.fc29.x86_64
 Go version:      go1.11beta2
 Git commit:      accfe55-unsupported
 Built:           Wed Jul 25 18:54:07 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-62.git9cb56fd.fc29.x86_64
 Go version:      go1.11beta2
 Git commit:      accfe55-unsupported
 Built:           Wed Jul 25 18:54:07 2018
 OS/Arch:         linux/amd64
 Experimental:    false
```

- Output of `docker info`:

```
Containers: 11
 Running: 0
 Paused: 0
 Stopped: 11
Images: 87
Server Version: 1.13.1
Storage Driver: overlay2
 Backing Filesystem: btrfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: journald
Cgroup Driver: systemd
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
 Authorization: rhel-push-plugin
Swarm: inactive
Runtimes: oci runc
Default Runtime: oci
Init Binary: /usr/libexec/docker/docker-init-current
containerd version: accfe55885ee1ff20e0479d2db23743d470c6b7e (expected: aa8187dbd3b7ad67d8e5e3a15115d3eef43a7ed1)
runc version: accfe55885ee1ff20e0479d2db23743d470c6b7e-dirty (expected: 9df8b306d01f59d3a8029be411de015b7304dd8f)
init version: N/A (expected: 949e6facb77383876aeff8a6944dde66b3089574)
Security Options:
 seccomp
  WARNING: You're not using the default seccomp profile
  Profile: /etc/docker/seccomp.json
 selinux
Kernel Version: 4.19.10-300.fc29.x86_64
Operating System: Fedora 29 (Workstation Edition)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 2
CPUs: 4
Total Memory: 7.69 GiB
Name: x1
ID: X4XU:CBUQ:JWWO:GVIC:3GZS:7ZCG:XUWZ:HJBH:37IB:MIZL:LUJW:TPVW
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: true
Registries: docker.io (secure), registry.fedoraproject.org (secure), quay.io (secure), registry.access.redhat.com (secure), registry.centos.org (secure), docker.io (secure)
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.22.0, build f46880f
docker-py version: 3.5.0
CPython version: 3.7.1
OpenSSL version: OpenSSL 1.1.1 FIPS  11 Sep 2018
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Test run on Fedora 29 Workstation on a ThinkPad (planning to run the containers on another docker host for prod later).

**Comment by stefangweichinger** [comment]
moved to other server and rewrote my yml to use persistent volumes, it works now, so: SOLVED

While we're at it ;-)  ... how to set up that container so that I can proxy it behind an apache on the docker host?
I tried:

```
# /var/lib/docker/volumes/redmine_redmine-persistence/_data/redmine/conf/environment.rb
Redmine::Utils::relative_url_root = "/redmine"
```

and

```
# apache vhost
<Location /redmine>
    ProxyPass http://127.0.0.1:8080
    ProxyPassReverse http://127.0.0.1:8080
    Require all granted
</Location>
```

yes, I fwd the redmine-port 3000 to 8080 on the docker host. I get redmine start page, but the generated links don't contain the sub-URI.

**Comment by andresbono** [comment]
Hi @stefangweichinger, as explained here:

http://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI

You need to restart the services after modifying the `conf/environment.rb`. Did you restart the container?

**Comment by stefangweichinger** [comment]
sure, every time after modifying docker-compose. I also removed the volumes etc

In the meantime I tried another image and filed two new issues there ;-)

https://github.com/sameersbn/docker-redmine/issues/368

https://github.com/sameersbn/docker-redmine/issues/370

**Comment by andresbono** [comment]
Hi again @stefangweichinger, you can try the following:

1) Modify the `/opt/bitnami/redmine/config.ru` file in the container. You need to add two lines before and after `run Rails.application`. It will look like:

```ruby
# This file is used by Rack-based servers to start the application.

require ::File.expand_path('../config/environment',  __FILE__)
map ActionController::Base.config.try(:relative_url_root) || "/" do
run Rails.application
end
```

2) Add a line at the bottom of the `/bitnami/redmine/conf/environment.rb` file (you already did this before):

```ruby
Redmine::Utils::relative_url_root = "/redmine"
```

3) Stop and start the container

```
docker-compose restart redmine
```

Note that the `/opt/bitnami/redmine/config.ru` file is not persisted. So if your container is deleted, you will need to apply the changes again. To solve that, you can mount it as a volume.

Let us know if this works for you.

**Comment by stefangweichinger** [comment]
I have it as a volume, ok. But how to edit that file, no vim or nano in the container per default? thx

**Comment by stefangweichinger** [comment]
found answer: https://github.com/bitnami/bitnami-docker-mongodb/issues/79#issuecomment-314415648

**Comment by stefangweichinger** [comment]
Applied the suggested changes after installing vim, restarted container.
Browser now brings me "Not Found: /"

**Comment by stefangweichinger** [comment]
You are absolutely right! It works now as far as I see, thanks a lot.

For reference (parts of) my now working compose file:

```
version: '2'

services:

  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - MARIADB_ROOT_PASSWORD=OClskd47
    volumes:
      - 'redmine-bitnami-db:/bitnami'
  redmine:
    image: bitnami/redmine:latest
    environment:
      - REDMINE_USERNAME=myuser
      - REDMINE_PASSWORD=admin
      - REDMINE_DB_PASSWORD=OClskd47
      - SMTP_HOST=somehost
# and more
    ports:
      - '3001:3000'
    volumes:
      - 'redmine-bitnami-app:/bitnami'
      - './config.ru:/opt/bitnami/redmine/config.ru'

volumes:
 redmine-bitnami-db:
 redmine-bitnami-app:
```

**Comment by andresbono** [comment]
Great! 🎉 Thanks for sharing the docker-compose.

**Comment by stefangweichinger** [comment]
I suggest adding the "how to deploy to Sub-URI" to the main documentation (README.md)
