### ISSUE TITLE
plesk bitnami docker failed to connect mariadb and too many symbolic links encountered

### ISSUE THREAD

**Issue by szejkindudi** [bitnami/bitnami-docker-redmine#110]
Latest version of plesk and bitnami docker redmine.
If I try first run new docker image there are problems show below and i can not docker attach (terminal hangs)

nami    INFO  Initializing redmine
redmine INFO  Configuring Redmine database...
mysql-c INFO  Trying to connect to MySQL server
nami    INFO  Initializing redmine
[0m
[0m[1mWelcome to the Bitnami redmine container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-redmine[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-redmine/issues[0m
[0m
Error executing 'postInstallation': Failed to connect to mariadb:3306 after 36 tries
[0m
[0m[1mWelcome to the Bitnami redmine container[0m
[0mSubscribe to project updates by watching [1mhttps://github.com/bitnami/bitnami-docker-redmine[0m
[0mSubmit issues and feature requests at [1mhttps://github.com/bitnami/bitnami-docker-redmine/issues[0m
[0m
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'

**Comment by javsalgar** [comment]
Hi,

Could you share the docker-compose.yml that you used? This way we can reproduce the issue.

**Comment by szejkindudi** [comment]
there i can find this file? on docker container or on host system?

pon., 21 sty 2019 o 09:21 Javier J. Salmerón-García <
notifications@github.com> napisał(a):

**Comment by javsalgar** [comment]
It should be found in the host system. Could you provide more details on how you launched the container?

**Comment by szejkindudi** [comment]
Launched by graphic interface from plesk (extensions):
https://www.plesk.com/blog/product-technology/plesk-docker-extension/ . On
the plesk site there tell: You cannot use the Docker Compose tool and its
configuration files
Should be in the host but i can see it.

wt., 22 sty 2019 o 09:09 Javier J. Salmerón-García <notifications@github.com>
napisał(a):

**Comment by javsalgar** [comment]
If you are not using docker-compose, then you need to launch first a mariadb container and have the Redmine container connect to it. I am afraid we do not have experience with the Plesk Docker Extension, so I do not know if that system has some constraints in order to make it work.

**Comment by szejkindudi** [comment]
Hello Javier.
BItnami Redmine at docker technology is not integated inside the container
with database? In my opinion database must be integrated with application
inside container that is strategy of docker - integrated work environment
but it looks like that search connection to external database (outside the
docker) but I can be wrong...
Plesk Docker Extension it is a simply managament add-one to manage docker
images. It Can search, download and run docker images.
When I try run fresh docker image it showin the logs:
redmine logs

nami    INFO  Initializing redmine
redmine INFO  Configuring Redmine database...
mysql-c INFO  Trying to connect to MySQL server
nami    INFO  Initializing redmine
 [0m
 [0m [1mWelcome to the Bitnami redmine container [0m
 [0mSubscribe to project updates by watching
[1mhttps://github.com/bitnami/bitnami-docker-redmine [0m
 [0mSubmit issues and feature requests at
[1mhttps://github.com/bitnami/bitnami-docker-redmine/issues [0m
 [0m
 [0m
 [0m [1mWelcome to the Bitnami redmine container [0m
 [0mSubscribe to project updates by watching
[1mhttps://github.com/bitnami/bitnami-docker-redmine [0m
 [0mSubmit issues and feature requests at
[1mhttps://github.com/bitnami/bitnami-docker-redmine/issues [0m
 [0m
Error executing 'postInstallation': ELOOP: too many symbolic links
encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'
 [0m
 [0m [1mWelcome to the Bitnami redmine container [0m
 [0mSubscribe to project updates by watching
[1mhttps://github.com/bitnami/bitnami-docker-redmine [0m
 [0mSubmit issues and feature requests at
[1mhttps://github.com/bitnami/bitnami-docker-redmine/issues [0m
 [0m

I can connect to docker for a while
docker exec -it e8a6fafce10e bash
but one moment after container restart.
I try few other version of bitnami/docker but have same issue.


czw., 24 sty 2019 o 09:33 Javier J. Salmerón-García <
notifications@github.com> napisał(a):

**Comment by javsalgar** [comment]
Hi

>  In my opinion database must be integrated with application
inside container that is strategy of docker

Nowadays, most of the examples you will find would deploy two containers, one for the database and another for the web application. This is the best practice as we  want to isolate (as much as possible) each process in a different container. This guide should help you: https://github.com/bitnami/bitnami-docker-redmine#run-the-application-manually

**Comment by szejkindudi** [comment]
Now everything it is clear. Thanks for support.

pon., 28 sty 2019 o 09:15 Javier J. Salmerón-García <
notifications@github.com> napisał(a):
