### ISSUE TITLE
Docker stop or constantly restarting

### ISSUE THREAD

**Issue by szejkindudi** [bitnami/bitnami-docker-redmine#111]
on a plesk 17.8.11 (ubuntu 16.04) few version of docker constantly restarting or stopping. In the log i see Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'
Problem is with latest and 3.4.7-ol-7-r15 and others vesions

**Comment by javsalgar** [comment]
Hi, 

We will need more information about how to reproduce it. It would be helpful for us if you could share your docker-compose.yml file

**Comment by Limbolindi** [comment]
`   
 redmine:
        image: bitnami/redmine:latest
        container_name: myredmine
        ports:
           - 127.0.0.1:${DOCKER_myredmine}:3000
        volumes:
           - redmine_data:/bitnami
        depends_on:
           - sqlDB
        links:
           - sqlDB:db        
        env_file:
           - redmine.env
`
Same issue.
The ENV - file stpecs the db user/pw and the ${DOCKER_...} is the proxyPort

**Comment by javsalgar** [comment]
I do not see anything strange that would trigger the issue. Just to confirm the issue occurs in the persistence, could you try removing the volumes section above?
