### ISSUE TITLE
Please add mounting redmine logs as volume

### ISSUE THREAD

**Issue by KrisTheGreat** [bitnami/bitnami-docker-redmine#112]
Hi,
Please add option to mount redmine logs as volume (/opt/bitnami/redmine/logs). I need to have a access to /opt/bitnami/redmine/logs/production.log for fail2ban on the host.

**Comment by marcosbc** [comment]
Hi @KrisTheGreat, the container prints the application log to stdout/stderr. You can see it with `docker logs CONTAINERID`.

If you are using docker-compose, there are a lot of ways you can achieve this, e.g.: https://stackoverflow.com/questions/35414495/save-docker-compose-logs-to-a-file
