### ISSUE TITLE
Cannot upload file bigger then 1 MB

### ISSUE THREAD

**Issue by KrisTheGreat** [bitnami/bitnami-docker-redmine#116]
Hi,

I can't upload to redmine any files which size is greater than 1MB. When I try to do so redmine displays an error "file is invalid" and the file is not uploaded.

  Redmine version                4.0.0.stable
  Ruby version                   2.4.5-p335 (2018-10-18) [x86_64-linux]
  Rails version                  5.2.2
  Environment                    production
  Database adapter               Mysql2
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp

Redmine is proxied on the host using nginx if this matters.

**Comment by andresbono** [comment]
Hi @KrisTheGreat, are you setting `client_max_body_size` property in the nginx server?
