### ISSUE TITLE
Support a way to install custom plugins 

### ISSUE THREAD

**Issue by juan131** [bitnami/bitnami-docker-redmine#118]
**Description**

As a Bitnami Redmine user, I'd like the Docker image to offer me a way to indicate a series of plugins so they're automatically installed during the container's initialisation.

**Additional information you deem important**

A possible approach would be having a Volume where the user can mount the desired plugins (ZIP format) so the init logic can detect and install them. (see the [approach used on MariaDB to execute custom SQL scripts](https://github.com/bitnami/bitnami-docker-mariadb#initializing-a-new-instance)).

**Comment by juan131** [comment]
I'm creating an internal task to address this feature request.

**Comment by juan131** [comment]
Just adding a comment so this issue continues opened.

**Comment by zx1986** [comment]
```
 nami    INFO  Initializing redmine
 redmine INFO  Redmine has been already initialized, restoring...
 mysql-c INFO  Trying to connect to MySQL server
 mysql-c INFO  Found MySQL server listening at docker.for.mac.localhost:3306
 mysql-c INFO  MySQL server listening and working at docker.for.mac.localhost:3306
 redmine INFO  Generating new secret...
 Error executing 'postInstallation': bundler: failed to load command: rake (/opt/bitnami/redmine/vendor/bundle/ruby/2.6.0/bin/rake)
 Bundler::ProductionError: You are trying to install in deployment mode after changing
 your Gemfile. Run `bundle install` elsewhere and add the
 updated Gemfile.lock to version control.

 If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze
 by running `bundle install --no-deployment`.

 The dependencies in your gemfile changed

 You have added to the Gemfile:
 * jwt (~> 1.5)
 * redmine_crm
 * svg-graph
 * prawn (~> 1.0.0)
 * wicked_pdf
 * wkhtmltopdf-binary
 * redmine_crm
 * vcard (~> 0.2.8)
 * spreadsheet (~> 0.6.8)
 * json

 You have deleted from the Gemfile:
 * pg (~> 1.1.4)

   /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/definition.rb:466:in `ensure_equivalent_gemfile_and_lockfile'
   /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/runtime.rb:13:in `setup'
   /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler.rb:107:in `setup'
   /opt/bitnami/ruby/lib/ruby/gems/2.6.0/gems/bundler-2.0.2/lib/bundler/setup.rb:20:in `<top (required)>'
   /opt/bitnami/ruby/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
   /opt/bitnami/ruby/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

I got those errors with some plugins which require additional gems.

**Comment by zx1986** [comment]
It seems like when I volume the plugins into Bitnami Redmine, 
and before the passenger start, it didn't `bundle install`, if some plugins has the its owner Gemfile need something new.

**Comment by juan131** [comment]
You're right @zx1986 ! The easiest way to include your own plugins by default in the image is to build your own image (create a new Dockerfile) based on the Bitnami image.

We have an internal task to support a way to indicate the pulgins to install on 1st run but that task is in our backlog and I'm afraid we didn't find bandwidth to work on that task yet.

**Comment by rosch100** [comment]
I am also interested in using plugins with redmine. As long as I would need my own image based on the Bitnami image - are you aware of a "howto" describing how to do that?

**Comment by juan131** [comment]
Hi @rosch100 

We don't have any how-to guide for this specific scenario but we did similar guides for development containers (such as Node.js):

- https://docs.bitnami.com/containers/how-to/deploy-custom-nodejs-app-bitnami-containers/

**Comment by kgurnani** [comment]
I had problems installing redmine_agile plugin with this image and tried creating a dockerfile and adding a `COPY plugin_name /opt/bitnami/redmine/plugins/plugin_name` as mentioned [here ](https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005) but it still didn't work and I ended up getting a `Gemfile.lock` error. The way I got the plugin to install was to:

1. Follow the exact steps listed in the readme and get the container running successfully.
2. Open another terminal tab/window and run `docker ps` to get the name of the container running redmine, mine was named redmine_redmine_1.
3. Unzip all themes and plugins I wanted to install in the same directory as the `docker-compose.yml` file.
4. Run `docker cp purplemine redmine_redmine_1:/opt/bitnami/redmine/public/themes`. This copies the [purplemine](https://github.com/mrliptontea/PurpleMine2) theme into the themes directory in the container.
5. Run `docker cp redmine_agile redmine_redmine_1:/opt/bitnami/redmine/plugins`. This copies the redmineup agile plugin in the plugin directory. 
6. Run `docker exec -it redmine_redmine_1 /bin/bash` to get a bash shell in the container.
7. Run `cd /opt/bitnami/redmine` in the bash shell we just got to get into de redmine directory.
8. Run `bundle config unset deployment` to remove the deployment var in the config.
9. Run `bundle install` to install redmine_agile dependencies.
10. Run `bundle config set --local deployment true` to set the deployment var to true again.
11. Run `bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production` to run rake tasks for the plugin.
12. Run `exit` to exit the container's bash.
13. Restart the container by running `docker restart redmine_redmine_1`.
13. Go to localhost:port or wherever you have redmine running and check if themes and plugins are properly installed.

**Comment by juan131** [comment]
Hi @kgurnani 

According to the steps you mentioned, I guess that you should be able to install it using a Dockefile like the one below:

```Dockerfile
FROM bitnami/redmine:4

RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev
WORKDIR /opt/bitnami/redmine
COPY purplemine redmine_redmine_1 /opt/bitnami/redmine/public/themes
COPY redmine_agile /opt/bitnami/redmine/plugins/redmine_agile
RUN bundle config unset deployment && \
    bundle install && \
    bundle config set --local deployment true && \
    bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production
```

**Comment by kgurnani** [comment]
Thanks @juan131  

I tried the dockerfile and it still didnt install the themes and plugins. I have already setup my installation as I wanted but I commented the steps I took if someone else is having the same problem as me so they can try it out and see if it works for them.

**Comment by juan131** [comment]
Hi @kgurnani 

I edited the Dockerfile (there was a typo). It should work since I used the same steps you previously mentioned.

> I have already setup my installation as I wanted but I commented the steps I took if someone else is having the same problem as me so they can try it out and see if it works for them.

Thanks so much for that! We really appreciate it.

**Comment by danninov** [comment]
I success add custom theme and plugins (redmine_openid_connect) with this Dockerfile.

```
FROM bitnami/redmine:4.1.1

RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev
WORKDIR /opt/bitnami/redmine
COPY purplemine2 /opt/bitnami/redmine/public/themes/purplemine
COPY redmine_openid_connect /opt/bitnami/redmine/plugins/redmine_openid_connect
RUN bundle config unset deployment && bundle install --no-deployment
```

**Comment by juan131** [comment]
Great!! Thanks so much for sharing it!!

**Comment by erSitzt** [comment]
How does this apply to plugins that require database migrations ?

**Comment by FraPazGal** [comment]
Hello @erSitzt,

From what it was discussed in another issue https://github.com/bitnami/bitnami-docker-redmine/issues/155#issuecomment-698970661, there are plugins where migrations are working fine. Nevertheless, keep in mind this feature is not yet implemented and there may be instances where some in-depth work could be required.

**Comment by marcosbc** [comment]
Hi, FYI we recently released a new container version, [4.2.1-debian-10-r70](https://github.com/bitnami/bitnami-docker-redmine#421-debian-10-r70). The initialization logic has received a major refactor, and its scripts are now located in the [`rootfs/` directory](https://github.com/bitnami/bitnami-docker-redmine/blob/master/4/debian-10/rootfs/).

Now that the initialization scripts are open-sourced in this repository, it would be great if anyone wants to contribute the changes to support this feature, we'll be glad to help with the review and release processes.

**Comment by ColdIce1** [comment]
One thing about plugins is that you need to run `bundle install`, but that may need to compile Ruby Gems from their natives which in turn needs the following development packages: `ruby-dev g++ gcc libssl-dev`. How would one go about installing ruby-dev when the default package with Debian 10 is 2.5 not 2.6 as installed with Bitnami

**Comment by juan131** [comment]
Hi @ColdIce1 

We highly recommend to extend the image for customizations that requires compilation, specially when these ones require installing development system packages that are not necessary for runtime.

**Comment by carrodher** [comment]
Hi, unfortunately, if the issue is not solved in recent versions means the task is still on our backlog and there are no plans to work on it in the short/middle term.

In the same way, please, [note the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution) since this asset was marked as a “Community supported solution”.

At this point, the best option to fix any issue or add a new feature is to contribute create a PR; the Bitnami team will be happy to review it and provide feedback.
