### ISSUE TITLE
need customize root path of redmine

### ISSUE THREAD

**Issue by alycat-Yan** [bitnami/bitnami-docker-redmine#120]
As a redmine user, I hope to customize the root path of redmine. I could not find where and how to change the root path, when there are many docker instances running under one nignx. 

 I google out there is a configuration could change the redmine resource root path ` config.relative_url_root = '/redmine' `, it change the resources path from `http://xxx.xxx.xxx/xxx.js` to `http://xxx.xxx.xxx/redmine/xxx.js` , but when i try to login, the login path is still use the default root path like `http://xxx.xxx.xxx/login`. Is there any way to change the root path? both work on resource and functional?

**Comment by andresbono** [comment]
Hi @alycat-Yan, can you take a look at this issue and let us know if it helps you?

https://github.com/bitnami/bitnami-docker-redmine/issues/119.

If you need further help after reading the issue above, just ask!

**Comment by alycat-Yan** [comment]
Thanks a lot. But it's strange. Shouldn't the root path be set in configuration.yml?
