### ISSUE TITLE
How to migrate from one docker environment to another

### ISSUE THREAD

**Issue by PierreSmits** [bitnami/bitnami-docker-redmine#121]
I have the redlmine container to work with mysql in one development/test instance, but now need to move it to another where acceptance tests are taking place.

The construct I used on the development instance was:
`
docker run -d --name ticket --network=redmine_network  -p 3000:3000 
 -e REDMINE_USERNAME=<adminId> 
-e REDMINE_PASSWORD=<adminPassword> 
-e REDMINE_DB_MYSQL=<IpAddressOfTestDb> 
-e REDMINE_DB_PASSWORD=<TestDbPassword> 
-v /vol/docker/ticket/data/redmine:/bitnami bitnami/redmine
`
and I have seen the configuration.yml and database.yml in the appropriate folder on /vol created. 

What do I need to take into account when pulling the container in the new test environment? Is simply copy-pasting the yaml files into the new environment enough to get the container running against the same database?

Best regards,

Pierre

**Comment by miguelaeh** [comment]
Hi @PierreSmits ,
The containers persists the configuration into the volume, in that case into `/bitnami`, in this way they are able to run with the same configuration each time they are stoped. To have the exactly same container you should migrate the volume too, so when you start it in the new environment it would have the same configuration as in the older one.

**Comment by PierreSmits** [comment]
Hi @miguelaeh,

Thank you for the fast reaction.

Yes, I have established the same folder structure on the new test instance, and copied over the files from the dev instance.

The question is: do I have to trigger the run command with the same environment parameters set as I initially did in the dev instance? After that initial trigger, I only used:
`docker restart ticket` 
to get it running again after shutdown.

Best regards,

**Comment by miguelaeh** [comment]
In theory the value of those env vars should be used in the configuration stage and they wouldn'd be necessary. But if you use them you ensures it will not fail in case of they are needed. So I would use the same command. Also, you need to mount the volume, and the network and name is related to Docker itself.
In short, the same command should work. But probably not setting the env vars will work too.
