### ISSUE TITLE
How to backup the Redmine from docker(Synology) to Windows?

### ISSUE THREAD

**Issue by luckygg** [bitnami/bitnami-docker-redmine#122]
**Description**
Hi all.

I think this is not an issue, but I can't find the solution.

I have a question about the backup of the Redmine.

I'm using the Redmine(v 3.3.6) on the Synology docker.

And I want to back up the Redmine data from the docker to the Windows.

But I don't know which data are required and how to move the data.

Could you please let me know how to back up from the Docker's Redmine to the Windows's Redmine?

Thank you :)

**Comment by marcosbc** [comment]
Hi @luckygg, unfortunately we are unfamiliar with the Synology Docker image and we cannot provide support for it.

However, I guess you want to migrate the data from the Synology Docker to the Bitnami Redmine stack on Windows. If so, this is the instructions we have for migrate/upgrade on the Bitnami installer: https://docs.bitnami.com/installer/apps/redmine/administration/upgrade/

Those steps would need to be adapted for the Synology container (e.g. it does not have `ctlscript.sh` and the MySQL connection would be different), but that should be enough to get you started.

If you have questions on how to do this, I'd advise you to ask in the [Synology community](https://community.synology.com/enu) in order for they to give instructions on how to export data from their Redmine Docker image.

**Comment by luckygg** [comment]
Hi @marcosbc 
Thank you for your advice.
I will ask it the Synology community.

Thank you.
