### ISSUE TITLE
Wrong variable name in Readme.md

### ISSUE THREAD

**Issue by pacoalcaide** [bitnami/bitnami-docker-redmine#123]
Substitute REDMINE_LANG for REDMINE_LANGUAJE in Readme.md

Thats all.

**Comment by marcosbc** [comment]
Hi @pacoalcaide, thanks for pointing it out! You are right, it should be `REDMINE_LANGUAGE`. We've change it, it should be reflected tomorrow morning once a new revision of the container has been released.

**Comment by marcosbc** [comment]
It was successfully changed in the README, so I'm proceeding to close this issue.
