### ISSUE TITLE
Error executing 'postInstallation': Group '2001' not found

### ISSUE THREAD

**Issue by Alexei-Kornienko** [bitnami/bitnami-docker-redmine#124]
Unable to install redmine in k8s using stable/redmine chart.
Persistent volumes are managed by glusterfs and overall this issue seems to be duplicate of https://github.com/bitnami/bitnami-docker-drupal/issues/88

**Comment by alemorcuq** [comment]
Hi, @Alexei-Kornienko.

We have not done any progress regarding this issue. However, would setting manually the uid and the gid with GlusterFS work for you? I found this: https://github.com/gluster/glusterfs/issues/262#issuecomment-314990868

Regards,
Alejandro

**Comment by Alexei-Kornienko** [comment]
Hi, @alemorcuq.
I decided not to touch gluster volumes by hand cause I'm using lots of automated CI pipelines and they are not supposed to work with manual interactions. 
I was considering fixing the bitnami image for redmine. I'm working with various Bitnami images for some time already and I have some knowledge of Bitnami images structure and how they work. To tell the truth I found image structure to be very complicated and hard to fix.
I was not able to deploy your chart with default redmine image cause it passes ENV variables with names other than expected by default image.
Cause of this I just spend 1 hour to write my own chart that uses default redmine image and it works fine..

**Comment by alemorcuq** [comment]
Hi, @Alexei-Kornienko.

Thank you for the feedback. It would be great if you could share with us any thoughts you have regarding the structure of our images. What did you find hard or complicated?

Regards,
Alejandro

**Comment by Alexei-Kornienko** [comment]
Hi @alemorcuq .
I worked with several bitnami images including redmine, phpbb, moodle.
Most of the issues I've had were related to the fact that images does not come 100% ready to work and instead they do some initialization logic during first start. I needed to customize images with custom plugins, themes, minor code changes etc. It's really hard to integrate such customizations without knowing how image  initialization is done and I was not able to found any documentation describing this process. In addtion Dockerfile that is available on github is far from being verbose and obvious about how it's built. I had to reverse engineer image structure and entrypoints to discover what is actually being done and how do I put my code inside of them without breaking anything. Another issue I see is that Container stores it's configuration (that is generated during init) on the outside volume and this makes it hard to actually update this configuration with each new release that is pushed by CI server. I would prefer to provide such configuration via env variables or configmap however I was not able to do it since bitnami container overwrites any kind of mounts that are provided with it's own symlinks to persistent volume. All of this makes it really painfull for me to do anything that goes beyond default installation

**Comment by alemorcuq** [comment]
Hi, @Alexei-Kornienko.

We are a aware that customizing our images can be a bit hard due to the hidden nami logic. To address this, we are in the process of migrating our containers to bash (see [mariadb](https://github.com/bitnami/bitnami-docker-mariadb) or [nginx](https://github.com/bitnami/bitnami-docker-nginx), for example). We are still early in the process, but we will eventually get there.

As for not persisting configuration, that's something we also have started to address. We have started with the infrastructure containers and we will start with applications when we are done. Again, it's still early, but we will get there.

Thank you very much for your valuable feedback.

Regards,
Alejandro

**Comment by eduard0lima** [comment]
> Hi, @alemorcuq.
> I decided not to touch gluster volumes by hand cause I'm using lots of automated CI pipelines and they are not supposed to work with manual interactions.
> I was considering fixing the bitnami image for redmine. I'm working with various Bitnami images for some time already and I have some knowledge of Bitnami images structure and how they work. To tell the truth I found image structure to be very complicated and hard to fix.
> I was not able to deploy your chart with default redmine image cause it passes ENV variables with names other than expected by default image.
> Cause of this I just spend 1 hour to write my own chart that uses default redmine image and it works fine..

I am experiencing a similar error:

[[stable / redmine] Error executing 'postInstallation': Group '99' not found
](https://github.com/helm/charts/issues/18118)
Could you solve this problem by creating another image? Could you provide the solution?

Thankful!

**Comment by Alexei-Kornienko** [comment]
@eduard0lima I used default image provided by redmine - https://hub.docker.com/_/redmine and just a basic helm chart built according to redmine installation manual:
1) include DB in chart requirements
2) Create and mount persistent volume to /usr/src/redmine/files

Unfortunately I'm not able to provide you with a finished chart due to NDA :(
