### ISSUE TITLE
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'

### ISSUE THREAD

**Issue by PierreSmits** [bitnami/bitnami-docker-redmine#125]
**Description**

1. I created a docker compose file (docker-ticket.yml) based on the example in the git repo with following content:
```
version: '2'
services:
  redmine:
    environment:
      - REDMINE_USERNAME=admin
      - REDMINE_PASSWORD=bitnami1
      - REDMINE_EMAIL=pierre.smits@********  
      - REDMINE_DB_PASSWORD=*********
      - REDMINE_DB_MYSQL=10.0.0.30

    image: 'bitnami/redmine:latest'
    ports:
      - '3000:3000'
    volumes:
      - '/vol/docker/ticket/data:/bitnami'

volumes:
  redmine_data:
    driver: local
```
2. I fired up with
```
docker-compose -f docker-ticket.yml up
```
I got following result:
```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
redmine INFO  Redmine has been already initialized, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at 10.0.0.30:3306
mysql-c INFO  MySQL server listening and working at 10.0.0.30:3306
redmine INFO  Generating new secret...
redmine INFO  Migrating database...
Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/redmine/public/plugin_assets'
```
3. I retried with
```
docker-compose -f docker-ticket.yml up
```
and got:
```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
redmine INFO  Redmine has been already initialized, restoring...
Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'
```

The database got created on my mysql/ server, but then got nowhere.

**Version**

- Output of `docker version`:

```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        2d0083d
 Built:             Thu Jun 27 17:56:17 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       2d0083d
  Built:            Thu Jun 27 17:23:02 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

- Output of `docker info`:

```
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5MiB
Name: monitor
ID: WBTH:WQR7:4FTR:U5F3:ZJNR:QFWX:Z7SG:LR75:LPZ3:ZHOL:MFVV:4VDH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine


Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 16.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 992.5MiB
Name: monitor
ID: WBTH:WQR7:4FTR:U5F3:ZJNR:QFWX:Z7SG:LR75:LPZ3:ZHOL:MFVV:4VDH
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.8.0, build unknown
docker-py version: 1.9.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by PierreSmits** [comment]
Doing
1. docker-compose down, followed by
2. docker-compose up

resulted in:
`nl04748@monitor:~$ docker-compose down
Removing nl04748_redmine_1 ... done
Removing network nl04748_default
nl04748@monitor:~$ docker-compose up
Creating network "nl04748_default" with the default driver
Creating nl04748_redmine_1
Attaching to nl04748_redmine_1
redmine_1  | 
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | 
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | redmine INFO  Redmine has been already initialized, restoring...
redmine_1  | mysql-c INFO  Trying to connect to MySQL server
redmine_1  | mysql-c INFO  Found MySQL server listening at 10.0.0.30:3306
redmine_1  | mysql-c INFO  MySQL server listening and working at 10.0.0.30:3306
redmine_1  | redmine INFO  Generating new secret...
redmine_1  | redmine INFO  Migrating database...
redmine_1  | Error executing 'postInstallation': EPERM: operation not permitted, chown '/bitnami/redmine/public/plugin_assets'
nl04748_redmine_1 exited with code 1
`

**Comment by PierreSmits** [comment]
redoing a 'docker-compose up' resulted in:
`
Starting nl04748_redmine_1
Attaching to nl04748_redmine_1
redmine_1  | 
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | 
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | redmine INFO  Redmine has been already initialized, restoring...
redmine_1  | Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'
nl04748_redmine_1 exited with code 1
`

**Comment by marcosbc** [comment]
Hi @PierreSmits, your compose file works fine for us.

Could it be possible that `/vol/docker/ticket/data` is served via NFS or any other file sharing, and where chown is not permitted? If not, you able to run `sudo chown daemon:daemon /vol/docker/ticket/data` from outside the container?

**Comment by PierreSmits** [comment]
That was it (/vol is being served via NFS). I have corrected the situation. And now it is running smoothly.

Thanks you very much.
