### ISSUE TITLE
Database connection check failed without quote marks.

### ISSUE THREAD

**Issue by zx1986** [bitnami/bitnami-docker-redmine#126]
**Description**

When using ProxySQL as database backend, the database connection check failed.

**Steps to reproduce the issue:**

1. config database.yaml to connect through proxysql
2. redmine app startup
3. the database connection check failed.

**Describe the results you received:**

```
mysql-c TRACE [execute] Executing: mysql -N -P 6033 -h proxysql.server -uprojcets -p -e SHOW DATABASES;

mysql-c TRACE [execute] Result: {"code":1,"stdout":"","stderr":"ERROR 1045 (28000): ProxySQL Error: Access denied for user 'projcets'@'10.144.70.128' (using password: YES)\n"}
mysql-c DEBUG Cannot connect to MySQL server. Retrying in 5 seconds...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

I tested in the same pod, running `mysql -N -P 6033 -h proxysql.server -uprojcets -p -e 'SHOW DATABASES';` is ok.

**Version**

I am running in Kubernetes, using the stable helm redmine chart.

---

By the way, the external database config totally failed, if I give the root privileges,
that's another story ...
https://github.com/bitnami/bitnami-docker-redmine/issues/51

**Comment by zx1986** [comment]
I test the command on my local with MySQL 5.7 and it failed too:

```
$ mysql -v -u root -p -h 127.0.0.1 -e SHOW DATABASES;
Enter password:

ERROR 1049 (42000): Unknown database 'DATABASES'
```

**Comment by zx1986** [comment]
I thought that was my own typo ...

**Comment by rafariossaa** [comment]
Hi @zx1986,l
  I am glad you were able to solve the issue.
