### ISSUE TITLE
Support SSL cert / configuration

### ISSUE THREAD

**Issue by sticksmite** [bitnami/bitnami-docker-redmine#127]
**Description**

No way to configure SSL cert and run redmine via secure connection.

**Steps to reproduce the issue:**

Documentation provided here does not work: https://docs.bitnami.com/general/how-to/generate-install-lets-encrypt-ssl/#alternative-approach

**Describe the results you expected:**

Expect to be able to expose 3443 and run with 443:3443 with a way to install and verify cert in container.

**Comment by javsalgar** [comment]
Hi,

When using containers, the you would normally use a proxy in front of it (for example ingress in kubernetes). The instructions you mentioned are for our cloud images and installers.

In our helm chart we have options for SSL certificate configuration https://github.com/helm/charts/tree/master/stable/redmine
