### ISSUE TITLE
before password storaged in ldap, password plus salt

### ISSUE THREAD

**Issue by mdzddl** [bitnami/bitnami-docker-redmine#130]
before my password is storaged in ldap, password plus salt;so when i use redmine in ldap to identify user it doesnt work; how can l solve my problme , did redmine can provide this Features；thanks

**Comment by marcosbc** [comment]
Hi @mdzddl, this seems like a very specific issue to the Redmine application. Fortunately they have a guide on configuring it here: http://www.redmine.org/projects/redmine/wiki/RedmineLDAP

If you keep finding issues, it's better you check the official Redmine LDAP troubleshooting guide: http://www.redmine.org/projects/redmine/wiki/RedmineLDAP#Troubleshooting
