### ISSUE TITLE
Initializing redmine every restart is taking too long

### ISSUE THREAD

**Issue by franrebo84** [bitnami/bitnami-docker-redmine#132]
**Description**

I'm running bitnami/redmine:4 with a pre-existing mysql database. Every time I restart the container. The init process spent about 8 o 10 minutes in "Migrating Database"

I have a volume to persist the config and the init found that is not a new installation, but everytime the miigrating database is executed.

Is this normal? 

```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

nami    INFO  Initializing redmine
redmine INFO  Redmine has been already initialized, restoring...
mysql-c INFO  Trying to connect to MySQL server
mysql-c INFO  Found MySQL server listening at syndb.mysql.database.azure.com:3306
mysql-c INFO  MySQL server listening and working at syndb.mysql.database.azure.com:3306
redmine INFO  Generating new secret...
redmine INFO  Migrating database...
redmine INFO
redmine INFO  ########################################################################
redmine INFO   Installation parameters for redmine:
redmine INFO     Persisted data and properties have been restored.
redmine INFO     Any input specified will not take effect.
redmine INFO   This installation requires no credentials.
redmine INFO  ########################################################################
redmine INFO
nami    INFO  redmine successfully initialized

```

**Comment by franrebo84** [comment]
More info. After activating the NAMI_DEBUG variable, I'm seeing more detailed logs:

```
redmine INFO  Migrating database...
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,db:migrate
ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,redmine:plugins:migrate
redmine TRACE [configurePermissions] File to chown: /home/redmine
redmine TRACE [configurePermissions] File to chmod: /home/redmine
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/tmp
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/tmp
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/tmp/pdf
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/tmp/pdf
redmine TRACE [configurePermissions] File to chown: /bitnami/redmine/public/plugin_assets
redmine TRACE [configurePermissions] File to chmod: /bitnami/redmine/public/plugin_assets
redmine TRACE [configurePermissions] File to chown: /bitnami/redmine/files
redmine TRACE [configurePermissions] File to chmod: /bitnami/redmine/files
redmine TRACE [configurePermissions] File to chown: /opt/bitnami/redmine/logs
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/logs
redmine TRACE [configurePermissions] File to chmod: /opt/bitnami/redmine/logs
redmine INFO
redmine INFO  ########################################################################
redmine INFO   Installation parameters for redmine:
redmine INFO     Persisted data and properties have been restored.
redmine INFO     Any input specified will not take effect.
redmine INFO   This installation requires no credentials.
redmine INFO  ########################################################################
redmine INFO
nami    INFO  redmine successfully initialized

```

**Comment by jotamartos** [comment]
Hi @franrebo84,

Our solution runs the `db:migrate` and `redmine:plugins:migrate` commands during the initialization and restoring processes. This way, you can upgrade the application to a newer version.

https://github.com/bitnami/bitnami-docker-redmine#upgrade-this-application

These commands will take care of upgrading the database and the plugins to the new version's syntax. 

>The init process spent about 8 o 10 minutes in "Migrating Database"

Depending on the data you have in the database and the specifications of the machine, it will take more or less time to finish.

I hope this information helps.

**Comment by franrebo84** [comment]
Thanks for your reply @jotamartos !

So, there is no way to skip this if the container has already initialized redmine?

**Comment by jotamartos** [comment]
Hi @franrebo84 ,

I'm sorry, but that's not possible. 

Regards

**Comment by franrebo84** [comment]
ok! Thanks!

**Comment by RobertoCesar** [comment]
I'm having the same problem...
Could you please point to me where exactly (which command / moment / file) the `db:migrate` and `redmine:plugins:migrate` are executed? So we could create another image or a replace file in a layer to not run these commands everytime the container starts and, even so, have the other advantages of bitnami?

> Hi @franrebo84,
> 
> Our solution runs the `db:migrate` and `redmine:plugins:migrate` commands during the initialization and restoring processes. This way, you can upgrade the application to a newer version.
> 
> https://github.com/bitnami/bitnami-docker-redmine#upgrade-this-application
> 
> These commands will take care of upgrading the database and the plugins to the new version's syntax.
> 
> > The init process spent about 8 o 10 minutes in "Migrating Database"
> 
> Depending on the data you have in the database and the specifications of the machine, it will take more or less time to finish.
> 
> I hope this information helps.

**Comment by jotamartos** [comment]
Hi @RobertoCesar,

Those commands are executed by the Bitnami Redmine module that we include in the container. We unpack the files during build time 

```
RUN bitnami-pkg unpack redmine-VERSION --checksum CHECKSUM
```

and then initialize in the [app-entrypoint.sh script](https://github.com/bitnami/bitnami-docker-redmine/blob/master/4/debian-10/rootfs/app-entrypoint.sh) 

```
nami_initialize redmine
```

The logic it follows during the initialization is inside the /root/.nami directory. 

Sorry for the inconvenience.

**Comment by RobertoCesar** [comment]
Hi @jotamartos 

Thanks!
Before I found this issue, I opend the [issue 151](https://github.com/bitnami/bitnami-docker-redmine/issues/151) and @juan131 answered me that he has created a issue for the backlog, to use an environment variable to set if the desirable behaviour is NOT to migrate the database when the container is created like I mention it's possible in the docker redmine image (https://hub.docker.com/_/redmine).

Thank you to take into account my considerations!

**Comment by carrodher** [comment]
Thanks for letting us know, I just see the internal task created. I can't provide you an exact ETA for this task as it depends on other tasks in our backlog. I am going to reopen the other issue (the one that originated the task) and put the `on-hold` label, that is our workflow for issues that we need to do something on our side.
