### ISSUE TITLE
Problem to install Redmine plugins

### ISSUE THREAD

**Issue by vambertojr** [bitnami/bitnami-docker-redmine#133]
**Description**

I have a version of Docker Redmine + Postgres Bitnami running in my environment.
I was asked to install the redmine_agile plugin.After following the installation steps, I am unable to install the plugin

**Steps to reproduce the issue:**

== Install

* Copy redmine_agile plugin to {RAILS_APP}/plugins on your redmine path
* Run bundle install --without development test RAILS_ENV=production
* Run bundle exec rake redmine:plugins NAME=redmine_agile RAILS_ENV=production

**Describe the results you received:**

 **After executing the first command errors started to appear:**

Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Could not find gem 'redmine_crm' in any of the gem sources listed in your Gemfile.

**After adding the source to the Gemfile file, another error appeared:**

An error occurred while installing nokogiri (1.10.5), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.5' --source 'https: // rubygems.org /'` succeeds before bundling.

In Gemfile:
  redmine_crm was resolved to 0.0.50, which depends on
    rails was resolved to 6.0.1, which depends on
      actioncable was resolved to 6.0.1, which depends on
        actionpack was resolved to 6.0.1, which depends on
          actionview was resolved to 6.0.1, which depends on
            rails-dom-testing was resolved to 2.0.3 which depends on
              nokogiri

**After installing the build-essential patch ruby-dev zlib1g-dev liblzma-dev packages, the first command was executed without errors. After executing the second command another error appeared:**

rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/ opt / bitnami / ruby ​​/ bin / bundle: 23: in `load '
/ opt / bitnami / ruby ​​/ bin / bundle: 23: in `<main> '
(See full trace by running task with --trace)

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf583a
 Built:             Fri Oct 18 15:54:09 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf583a
  Built:            Fri Oct 18 15:52:40 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 5
  Running: 1
  Paused: 0
  Stopped: 4
 Images: 4
 Server Version: 19.03.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 4.15.0-66-generic
 Operating System: Ubuntu 18.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 2.931GiB
 Name: servtest1
 ID: THLF:FOB6:Q3R6:A4V3:5SN2:ORDH:Y3DZ:EWJT:SVVZ:OKDR:LABB:F7W5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.24.1, build 4667896b
docker-py version: 3.7.3
CPython version: 3.6.8
OpenSSL version: OpenSSL 1.1.0j  20 Nov 2018

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @vambertojr, can you take a look at https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005? It explains how to install the `redmine_agile` plugin. I hope this is useful!

**Comment by vambertojr** [comment]
Thank´s @andresbono It worked

**Comment by andresbono** [comment]
Great! 🎉
