### ISSUE TITLE
A possibility to set rails secret_key_base to static value

### ISSUE THREAD

**Issue by ErmakovDmitriy** [bitnami/bitnami-docker-redmine#134]
**Description**

In case of clustered deployment Rails requires equal secret for signing session cookies.
Current version of container does not allow setting equal secret.
I hope it is possible to add some method for configuring it.

**Steps to reproduce the issue:**

1. Deploy at least 2 containers with load balancer
2. Connect to Redmine and authenticate (load balancer, for instance, sends auth request to container 1)
3. Reload page multiple times (usually 2-5) in order to force load balancer to send new requests to container 2 which has different session signing secret.
4. Get authentication failure error

**Describe the results you received:** 
Authentication failure and no way to start multiple Redmine containers for load-balancing

**Comment by andresbono** [comment]
Hi @ErmakovDmitriy, can you share with us documentation on how to work with a rails/redmine clustered deployment?

**Comment by ErmakovDmitriy** [comment]
Hi @andresbono,

Here is a short algorithm of deployment:
1. Configure NFS server (I used it to allow multiple clients Read-Write access).
2. Configure supported SQL database.
3. Start multiple containers with the SQL DB from step 2 and mounting `/bitnami` inside the containers to NFS server from step 1.
4. Configure common Rails secret for signing session cookies.
5. Configure external load balancer to point to the containers from step 4.

I used Kubernetes for my deployment and Helm redmine chart.
The chart deploys Redmine + MySQL database and is intended for creating one Redmine Pod and one MySQL/PostgreSQL database instance (without replication). To support the algorithm above I used (step-by-step descriptions):
1. External NFS server + Kubernetes NFS provisioner
2. MySQL database was deployed by the Helm chart
3. Configured the Helm chart to deploy 2 replicas of Redmine containers (Pods under Deployment control)
4. To configure common secret I had to create custom Docker image based on your redmine. The only change is adding a step which starts all scripts from `/docker-init.d/` directory of the container. I modified your `run.sh`. 
Here is the modified file:

```shell
#!/bin/bash -e
. /opt/bitnami/base/functions
. /opt/bitnami/base/helpers

USER=redmine
RAILS_ENV=production
PID_FILE=/opt/bitnami/redmine/tmp/pids/redmine.pid
LOG_FILE=/opt/bitnami/redmine/logs/production.log

mkdir -p /opt/bitnami/redmine/tmp/pids
chown ${USER}: -R /opt/bitnami/redmine/tmp
chmod -R 1777 /opt/bitnami/redmine/tmp

# This step executes all scripts from /docker-init.d/
info "Executing user-defined init scripts"
if [ -e /docker-init.d/  ]; then
    cd /docker-init.d/

    run-parts --verbose --exit-on-error --regex=".+" ./
fi

info "Starting redmine..."
cd /opt/bitnami/redmine || exit 1
exec gosu ${USER} bundle exec passenger start -e ${RAILS_ENV} --pid-file ${PID_FILE} --log-file ${LOG_FILE} -p 3000
```

Your image performs automatic generation of Rails secret during startup and it leads to different secrets on all containers. I added a small script into `/docker-init.d/` directory (I used Kubernetes ConfigMap as Volume mechanism). The script just uses EnvVar as a shared secret.
Script to replace generated secret:

```shell
#!/usr/bin/env bash

cat << END > /opt/bitnami/redmine/conf/initializers/secret_token.rb

# This file was generated by custom script 'set-custom-rake-secret.sh', and should
# not be made visible to public.
# If you have a load-balancing Redmine cluster, you will need to use the
# same version of this file on each machine. And be sure to restart your
# server when you modify this file.
#
# Your secret key for verifying cookie session data integrity. If you
# change this key, all old sessions will become invalid! Make sure the
# secret is at least 30 characters and all random, no regular words or
# you'll be exposed to dictionary attacks.
RedmineApp::Application.config.secret_key_base = '$REDMINE_SECRET_TOKEN'

END
```

The `REDMINE_SECRET_TOKEN` environment variable are substituted by Kubernetes in my case.

5. Load balancing is performed by Kubernetes ingress + traefik.

This configuration allows me using 2 Pods of Redmine for load balancing and reducing downtime in case of some problems with one of the Pod.

**Comment by andresbono** [comment]
This is great @ErmakovDmitriy!! Thanks for sharing it. I'm sure other users will benefit from all the detailed steps that you are describing.

On our side, we will evaluate if we can add a new parameter for the `secret_key_base` property.

**Comment by ErmakovDmitriy** [comment]
Thank you!
I would like to see the property and the "custom script" features :)

**Comment by erSitzt** [comment]
@sameersbn @andresbono  was there anything done regarding this issue ?
i just ran into this with the bitnami helm chart when trying to use more than 1 replica...  which should be ok when using a readwritemany volume like nfs...

**Comment by andresbono** [comment]
Hi @erSitzt, I'm afraid that this issue has not been addressed yet. We are focusing our efforts on making the configuration logic available for the users and it is likely that this issue is resolved when it is the turn of refactoring Redmine.

**Comment by erSitzt** [comment]
It seems rails apps are aware of the env var `SECRET_KEY_BASE` when using the `production` environment.
Setting it to some value worked for me.

https://github.com/rails/rails/issues/32413#issuecomment-377907207

**Comment by andresbono** [comment]
Oh, that's great! 🎉  In that case, I'm going to close this issue. Thanks for sharing the solution!!

**Comment by erSitzt** [comment]
btw..
The docker official redmine image does use this too

https://github.com/docker-library/redmine/search?q=secret_key_base

![image](https://user-images.githubusercontent.com/1625376/112627035-5bd29080-8e31-11eb-8948-9c89a6ab15cd.png)

**Comment by andresbono** [comment]
Thanks for sharing, @erSitzt 👍
