### ISSUE TITLE
mssql db adapter support

### ISSUE THREAD

**Issue by koren85** [bitnami/bitnami-docker-redmine#137]
Hi!
How i can use mssql adapter? Is it possible?

**Comment by javsalgar** [comment]
Hi,

When we build redmine, we enable the mysql and postgresql extensions. At the moment we did not enable the sqlserver adapter gem. I will open a task for evaluating it and consider it for future releases of the container. I will update the ticket when we have more information.

**Comment by beltran-rubo** [comment]
It seems Redmine does not offer this option anymore https://www.redmine.org/projects/redmine/wiki/RedmineInstall

```
Redmine 4.0 does not support SQL Server as of December 2018 because a dependent library activerecord-sqlserver-adapter does not support Rails 5.2 yet.
```
