### ISSUE TITLE
Use of mariadb replication cluster in conjunction with Redmine

### ISSUE THREAD

**Issue by jonfen** [bitnami/bitnami-docker-redmine#141]
I have been unable to find any documentation around this, but is it recommended / possible to use the MariaDB Replication Cluster (https://github.com/bitnami/bitnami-docker-mariadb#setting-up-a-replication-cluster) in conjunction with Redmine?

**Comment by javsalgar** [comment]
That would depend on whether the application supports it or not. I do not recall Redmine having that feature. Did you consult the Redmine devs about that?

**Comment by jonfen** [comment]
> That would depend on whether the application supports it or not. I do not recall Redmine having that feature. Did you consult the Redmine devs about that?

What is the best way to contact the Redmine devs?

**Comment by javsalgar** [comment]
This should be the place: https://www.redmine.org/projects/redmine/boards
