### ISSUE TITLE
How to recovery redmine from docker image

### ISSUE THREAD

**Issue by zhouqiancheng** [bitnami/bitnami-docker-redmine#142]
Hi,
For some reasons my docker redmine is broken.
Before broken, I have backup the docker with 'docker save' to two '.tar' file. One for mariadb, another for redmine.

How can I recovery from the '..tar' file?

docker save c47a3aab505e > "C:\btnami_mariadb.tar"
docker save 56a699d1ce8b > "C:\btnami_redmine.tar"

My computer is windows 10.

**Comment by marcosbc** [comment]
Hi @zhouqiancheng, from the `docker save` documentation: https://docs.docker.com/engine/reference/commandline/save/, images created can be imported with `docker load`, i.e.:

    docker load < "C:\btnami_mariadb.tar"
    docker load < "C:\btnami_redmine.tar"

You should then see the new images:

    docker images

**Comment by zhouqiancheng** [comment]
Hi @marcosbc ，

It helps. But I am new to docker and redmine, I forgot to backup volume, I lost my data.

Regards,

**Comment by marcosbc** [comment]
@zhouqiancheng If you lost your volume, unfortunately there's little we can do about the data that was contained in the containers. The .tar will only contain the root file system "/" for the containers, excluding mounted volumes/files.

**Comment by zhouqiancheng** [comment]
@marcosbc Thanks， luckly not too much data lost. I just create a new version.

Do you have any suggestion on how to backup data and rep?

Currently, I backup all the vhdx file. I use docker desktop for Windows.
Any other methods are better than this?

Thanks

**Comment by marcosbc** [comment]
@zhouqiancheng Basically the fundamental part is that you need to backup the volume with persisted data. The data stored in the container image (generated via docker save) does not include the volume.

We've added some instructions below for backup/restore.

**Backup (mounted volume to file system)**

If you did not use Docker volumes (`docker volume`), but storing the data directly to your file system via mounted directories/volumes, you just need to backup those directories. This is as simple as running the command below:

    cd /path/to/volume
    tar czf /tmp/redmine_data_backup.tar.gz .

**Backup (Docker volumes)**

If you are using Docker volumes (`docker volume`), the container that you want to backup needs to be running. Run the command below, replacing `CONTAINER_ID` with the container name or identifier that includes the volume, which will result in a `redmine_data_backup.tar.gz` generated in the `backup` directory inside your current directory.

    docker run --rm --volumes-from=CONTAINER_ID -v $(pwd)/backup:/tmp bitnami/minideb tar czf /tmp/redmine_data_backup.tar.gz -C /bitnami/redmine .

**Restore**

Start the image you want to restore as if it had an empty volume, and run the commands below:

    docker cp backup/redmine_data_backup.tar.gz CONTAINER_ID:/tmp/redmine_data_backup.tar.gz
    docker exec -ti CONTAINER_ID bash -c "rm -rf /bitnami/redmine/* && tar xzf /tmp/redmine_data_backup.tar.gz -C /bitnami/redmine && rm /tmp/redmine_data_backup.tar.gz"
    docker restart CONTAINER_ID
