### ISSUE TITLE
How to install plugins in docker redmine?

### ISSUE THREAD

**Issue by zhouqiancheng** [bitnami/bitnami-docker-redmine#145]
Hi,
I try to install CKEditor. but get error during the installation. Any one can help? Thanks.

Here is my steps:
1. copy 'redmine_cke' to plugins dir.
2. go to plugins dir and run 'bundle install'

3. I try to solve issue2, so run 'bundle init'. problem solved
4. Run 'bundle install' again. 
![image](https://user-images.githubusercontent.com/24894175/74659770-e2995080-51cf-11ea-8b2e-b74964b357ca.png)
5. At last run 'rake redmine:plugins:migrate RAILS_ENV=production' to install. But get errors again.
![image](https://user-images.githubusercontent.com/24894175/74659844-065c9680-51d0-11ea-97d2-7f459fb7cd97.png)
Then I don't know how to get over this.  What can I do?

Regards

**Comment by zhouqiancheng** [comment]
error msg for step 2 is shown as below:
![image](https://user-images.githubusercontent.com/24894175/74660110-779c4980-51d0-11ea-838d-c9d41ded4f30.png)

**Comment by andresbono** [comment]
Hi @zhouqiancheng, please check https://github.com/bitnami/bitnami-docker-redmine/issues/115#issuecomment-468231005 in case it is of any help.
