### ISSUE TITLE
how can i install CSV and Subversion 

### ISSUE THREAD

**Issue by karippery** [bitnami/bitnami-docker-redmine#146]
I currently install your redmine docker  from your repository.  
in my task I want to migrate my redmine(host) to docker. 
for the first step i need to copy my redmine theme to your docker. for that i need **csv darcs bzr svn and hg**
when i install from your repository 

> SCM:
>   Git                            2.25.1
>   Filesystem 
> 

I need 

> Subversion                     1.9.7
>   Cvs                            1.12.13
> Darcs                          2.8.5
>   Git                            2.17.1
>   Filesystem  

I already try `apt install darcs and gem install csv`
but it is not showing in redmine

please help me

**Comment by marcosbc** [comment]
Hi @karippery,

>I already try `apt install darcs and gem install csv`
>but it is not showing in redmine

Unfortunately we don't have enough information to help you.

Could you describe your error? Also, can this error be reproducible with a public/free theme? Any information that may help us reproduce this issue on our side is helpful.

**Comment by karippery** [comment]
Hi @marcosbc 

I just want to  migrate my redmine to docker container
I copy theme folder from my redmine to docker /opt/bitnami/redmine/public
I copy plugins folder to docker opt/bitnami/redmine/plugins
and 
**I install necessary packages** 
 apt install build-essential libpq-dev pkg-config libmagickwand-dev ruby ruby-dev
**and I install necessary gems** 
gem install will_paginate 
gem install jenkins_api_client
gem install activesupport -v 4.2.8
gem install  haml-rails -v 1.0
gem install deface -v 1.0.2
gem install brakeman -v 4.8.0

**install plugins**
bundle exec rake redmine:plugins NAME=readme_at_repositories RAILS_ENV=production

**error** 

```
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.

If this is a development machine, remove the /opt/bitnami/redmine/Gemfile freeze 
by running `bundle config unset deployment`.

The dependencies in your gemfile changed

You have added to the Gemfile:
* jenkins_api_client (~> 1.5.3)
* haml-rails
```


i already try to add gem "jenkins_api_client " and gem "haml-rails" but i got same error.
