### ISSUE TITLE
I still have the same issue!

### ISSUE THREAD

**Issue by mahidhara** [bitnami/bitnami-docker-redmine#148]
Any chance you can share your final compose and dockerfile?
when I try this method, I am getting error with mysql:
Access denied for user 'bn_redmine'@'%' to database 'bitnami_redmine_EyCK4'

without the docker file, if I only use the compose.yml - I can install the redmine - but the plugin wont install.

really appreciate if someone can help!!

thanks you.

@tompizmor  thanks :)

![image](https://user-images.githubusercontent.com/26577860/41265594-dc24cde6-6da7-11e8-819f-6eb8d9ab413b.png)

_Originally posted by @ephisr in https://github.com/bitnami/bitnami-docker-redmine/issues/101#issuecomment-396439509_

**Comment by mahidhara** [comment]
version: '3.3'
networks:
  redminetier:
   external: true

volumes:
  redmine_data:
    external: true
  mariadb_data:
    external: true

services:
  mariadb:
    networks:
      - redminetier      
    container_name: mariadb
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
        - MARIADB_DATABASE=bitnami_redmine
    volumes:
        - 'mariadb_data:/bitnami'
    image: 'bitnami/mariadb:latest'

  redmine:
    networks:
      - redminetier      
    container_name: redmine
    ports:
        - '8080:3000'
    environment:
        - REDMINE_DB_NAME=bitnami_redmine
    volumes:
        - 'redmine_data:/bitnami'
    #image: 'bitnami/redmine:latest'
    depends_on:
      - mariadb
    build:
      context: .
      dockerfile: Dockerfile-agile


=========Dockerfile-agile=======
FROM bitnami/redmine:latest
ENV NODE_ENV="production"
RUN install_packages build-essential default-libmysqlclient-dev libpq-dev libmagickwand-dev
WORKDIR /opt/bitnami/redmine
COPY redmine_agile /opt/bitnami/redmine/plugins/redmine_agile
RUN bundle install --no-deployment

====================

This actually worked, but when I run:
` echo $BITNAMI_IMAGE_VERSION`

with Dockerfile, the version is: **4.0.1-debian-9-r21**
While, without the Dockerfile (directly using image: bitnami/redmine:latest)  i get redmine version: **4.1.1-debian-10-r4**

Any idea why and how I can get the latest version (4.1.1-debian-10-r4) through Dockerfile?

**Comment by Mauraza** [comment]
Hi @mahidhara,

In the docker-compose.yaml you posted I can't see the `MARIADB_USER`, and the `REDMINE_DB_USERNAME`. Could you try to add this environment variables and run again?

**Comment by mahidhara** [comment]
@Mauraza thank you for your reply.
When I have those parameters included, I keep getting error from mysql database:
`Access denied for user 'bn_redmine'@'%' to database 'bitnami_redmine_EyCK4'`

After I removed the MariaDB_User and redmine_db_username - the installation was successful. I can see the plugin as well.

But now the problem is that the latest version of Redmine is not getting installed even though my Dockerfile has: 
`FROM bitnami/redmine:latest

The version I was expecting to get was:
**4.1.1-debian-10-r4**
But the version that gets installed is:
**4.0.1-debian-9-r21**

**Comment by Mauraza** [comment]
Hi @mahidhara,

the error `Access denied for user 'bn_redmine'@'%' to database 'bitnami_redmine_EyCK4'` could happen if you run before, the volume still up. In this case, you can use `docker-compose down -v` to avoid this. 

To get the latest image, delete the image you have, `docker rmi id-image-redmine` and run again to get the image. 

I hope that helps you.

**Comment by mahidhara** [comment]
Hello @Mauraza ,
Thank you for the help.

The access denied is not going away even though I removed all volumes and images and start afresh. The only way this is working is if I have `FROM bitnami/redmine:4.0.1-debian-9-r21` in the DockerFile.

If I update it to latest, the gemfile lock error comes back up.

The only option that is working for me is to downgrade the build to 4.0.1 and without the mariadb_user.

Am i doing something wrong?

**Comment by Mauraza** [comment]
@mahidhara, could you update the issue with the gemfile lock error?
