### ISSUE TITLE
Deploying to a sub-URI: script causes unknown option to s

### ISSUE THREAD

**Issue by steschdkfz** [bitnami/bitnami-docker-redmine#150]
**Description**

I want to deploy to a sub-URI using docker-compose and followed the description given on this page. MariaDB container starts properly, but redmine ends with error:
200f48d1e376_dataforweb_redmine_1 | sed: -e expression #1, char 42: unknown option to `s'

**Steps to reproduce the issue:**

1. Follow the description using: docker-compose up.
(No -d to see echo)
(No other steps)

**Describe the results you received:**
200f48d1e376_dataforweb_redmine_1 | sed: -e expression #1, char 42: unknown option to `s'
200f48d1e376_dataforweb_redmine_1 exited with code 1

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Docker version 19.03.11, build 42e35e61f3
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 4
 Server Version: 19.03.11
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-1127.8.2.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.638GiB
 Name: xxxx
 ID: xxxx
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: xxxx
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.23.2, build 1110ad01
[yml_and_sh.zip](https://github.com/bitnami/bitnami-docker-redmine/files/4724401/yml_and_sh.zip)


```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by joancafom** [comment]
Hi @steschdkfz 

I have been able to reproduce your issue, thanks for reporting it! I have implemented some changes on the README and it will be updated in the following hours. On the meantime, you can change this line:

```
...
SUB_URI_PATH=$(echo ${SUB_URI_PATH} | sed -e 's|/|\/|g')
...
```
to this
```
SUB_URI_PATH=$(echo ${SUB_URI_PATH} | sed -e 's|/|\\/|g')
```
on `subUriInit.sh`. With that you should be able to deploy Redis in a sub-uri again!

Thanks!

**Comment by joancafom** [comment]
Closing this as README.md was already updated with the info!
