### ISSUE TITLE
Trying to configure my Redmine installation

### ISSUE THREAD

**Issue by pdcatbsc** [bitnami/bitnami-docker-redmine#155]
I have the Bitnami Redmine and PostgreSQL Docker containers installed on a Linux computer.  I'm trying to configure creating issues via an email.  I followed the instructions on the Bitnami documentation site, but nothing works because it's all inside the Docker container.  I used crontab -e and added the line in my cronfile to access redmine:email:receive_imap but of course it doesn't work because my server can't find bundle and there is no /opt/bitnami directory on my server.  I wasn't sure if I'm supposed to be doing something outside Docker to make this work or if I'm supposed to use a Docker command to edit something inside the container.  My installation has been working well since I got it going, but I can't figure out how to change anything outside the available environment variables.  Thanks.

**Comment by pdcatbsc** [comment]
Environment:
  Redmine version                4.1.1.stable
  Ruby version                   2.6.6-p146 (2020-03-31) [x86_64-linux]
  Rails version                  5.2.4.2
  Environment                    production
  Database adapter               PostgreSQL
  Mailer queue                   ActiveJob::QueueAdapters::AsyncAdapter
  Mailer delivery                smtp
SCM:
  Git                            2.28.0
  Filesystem                     
Redmine plugins:
  no plugin installed

**Comment by juan131** [comment]
Hi @pdcatbsc 

I guess you're following some of the guides intended for the Native installers or Single VMs we also offered packaging Redmine. For instance, the guide below:

- https://docs.bitnami.com/installer/apps/redmine/configuration/configure-smtp/

Please note that containers follow a different file structure and these guides don't apply to them.

In order to configure SMTP in the Redmine container, please follow the instructions detailed in the link below:

- https://github.com/bitnami/bitnami-docker-redmine#smtp-configuration

**Comment by pdcatbsc** [comment]
I haven't been able to find any Docker flavored Redmine documentation on Bitnami's website other than the readme file for the installation.  I am new to Docker and ignorant to its ways, but I was pointed to some good tutorials that I am beginning on.  I was able to make the SMTP notifications work on my Redmine installation, but I still have not been able to make the "importing email as an issue" function work because I cannot run the "rake redmine:email:receive_imap" command.  Everything I can find regarding Redmine operation/configuration outside of the actual web application is based on Bundle and Rake and those are inside the container.  

I was looking at another Redmine container and it had a lot more environment variables....  are those setup by the container author and those are the only variables applicable to that container?  In other words, if a variable is not configured in the Bitnami container that variable would not be available for my installation?  

Please know that I am asking these questions due to my ignorance and I am not complaining about the Bitnami stack.  I had this thing up and running in no time flat with no real knowledge of what I was doing and I've been very productive with my Redmine installation for the last couple weeks.  I'd probably still be pulling my hair out if I had just tried to install all the packages.  :)  I've also installed a couple other Bitnami stacks on VM machines and those were very easy to get up and going as well.  Thank you for your help Juan!

**Comment by juan131** [comment]
> I haven't been able to find any Docker flavored Redmine documentation on Bitnami's website other than the readme file for the installation.

We don't have a specific website for documentation related to the Bitnami Redmine container. Please refer to the README.md for any related question. It'll be also very useful to consult what other users asked in the [repository issues section](https://github.com/bitnami/bitnami-docker-redmine/issues?q=is%3Aissue).

> I was able to make the SMTP notifications work on my Redmine installation, but I still have not been able to make the "importing email as an issue" function work because I cannot run the "rake redmine:email:receive_imap" command. Everything I can find regarding Redmine operation/configuration outside of the actual web application is based on Bundle and Rake and those are inside the container.

You can still access the container using the `docker exec` command. That said, could you please specify the exact steps you followed to use that feature?

> I was looking at another Redmine container and it had a lot more environment variables.... are those setup by the container author and those are the only variables applicable to that container? In other words, if a variable is not configured in the Bitnami container that variable would not be available for my installation?

Every container's author is free to define its own environment variables, and we are not familiar with other implementations. The supported environment variables by the Bitnami Redmine container are documented in the link below:

- https://github.com/bitnami/bitnami-docker-redmine#configuration

> Please know that I am asking these questions due to my ignorance and I am not complaining about the Bitnami stack. I had this thing up and running in no time flat with no real knowledge of what I was doing and I've been very productive with my Redmine installation for the last couple weeks. I'd probably still be pulling my hair out if I had just tried to install all the packages. :) I've also installed a couple other Bitnami stacks on VM machines and those were very easy to get up and going as well. Thank you for your help Juan!

Don't worry, we totally understand there are several doubts when moving from VMs to containers.

The Bitnami containers  differ from the Bitnami VMs since they're more dynamic and configurable via env variables, and they're created following a cloud native mindset. While most advanced configuration (e.g. mail setup) on the VMs are documented and the instructions usually imply to access the VM via SSH and perform some actions, on containers we try to avoid providing instructions that implies accessing them since they're designed to be ephemeral and we try to provide a way to do it from the outside (e.g. using env. vars).

**Comment by pdcatbsc** [comment]
> We don't have a specific website for documentation related to the Bitnami Redmine container. Please refer to the README.md for any related question. It'll be also very useful to consult what other users asked in the [repository issues section](https://github.com/bitnami/bitnami-docker-redmine/issues?q=is%3Aissue).

I think it would be very beneficial to users if you'd modify all your README files to at LEAST have a comment at the top that you have to do something different if you're installing in a Docker environment.  Or maybe explain that the only way (or at least the only way a container's author has intended) to modify the installation is through the environment variables.  The variables are explained in the README file, but nothing in there says you can't just change config files and make changes to the container.  I had already installed Redmine a couple times and a couple other apps as well on Linux and in Linux VM's before I installed the Bitnami Docker Redmine.  I had read up on the benefits of Docker containers, but I had not read anything anywhere that said container authors will possibly change the entire directory structure, delete a ton of stuff you might be used to having access to (or never install it in the first place) to make their containers smaller and you can't just go in there and change config files around like you're used to doing.  As a newcomer to Docker, I spent weeks pulling my hair out, not just with Bitnami installations, but others as well before somebody basically told me, "Dude, you can't just do it like that.  It doesn't work like that."  :)  Again, I'm not knocking on Bitnami, it's just an observation based on my personal experience.

> > I was able to make the SMTP notifications work on my Redmine installation, but I still have not been able to make the "importing email as an issue" function work because I cannot run the "rake redmineemailreceive_imap" command. Everything I can find regarding Redmine operation/configuration outside of the actual web application is based on Bundle and Rake and those are inside the container.
> 
> You can still access the container using the `docker exec` command. That said, could you please specify the exact steps you followed to use that feature?
> 

I have a volume mounted (persisted?) outside the container where my data is.  In the \home\bitnami\redmine\conf\configuration.yml file I just added this:

email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "smtp-mail.outlook.com"
      port: 587
      authentication: :login
      user_name: "username@outlook.com"
      password: "password"

That allowed me to turn it on inside the application.  Inside the app I went to Administration - Settings - Email notifications and input my information.  Without the info in the configuration.yml file, you just get the error message that Email notifications are not enabled and you need to edit your config\configuration.yml file.  I've recently figured out that plugins work the same way, but I haven't gotten them to work yet.  Adding a plugin in my plugin directory outside the container causes Redmine on startup to run a plugins migration routine, but apparently, you have to do some work inside the container to load up some additional Gems it needs and I haven't got that going yet.  The one plugin I added to that directory caused the Redmine container to refuse to load at all.  I deleted the plugin from that directory and it fired right up.  So I'm getting there.  It's a very slow process, but bit by bit I'm figuring it out.  :)

> Every container's author is free to define its own environment variables, and we are not familiar with other implementations. The supported environment variables by the Bitnami Redmine container are documented in the link below:

I understand, that was a generic question relating to containers in general and not about that guy's specific container.  I'm coming to understand that a container is set up to be modified by that author's decision as to what environment variables to allow changing inside the container and nothing else.  The benefit being if the container is recreated or updated to a new version, there are not a bunch of changes inside the container that will be lost.  Make a couple variable changes externally to the startup file or however you start your container and you're right back up and going.  Again I think a one line comment at the top of all of Bitnami's README files that points to a short Docker info file somewhere telling new people that this is how it works with Docker.  If you want to completely customize your Redmine installation, or any other app for that matter, you might want to use the Win/Mac/Linux installer or set it up in a VM.  

Anyway.....  The email notification thing was pretty simple because I could modify an external config file and then make a config change inside the Redmine app.  The "create an issue by email" thing is still eluding me because you have to run a rake command inside the container to fire up the redmine:email:receive_imap routine and then once you get that working, you have to modify your cron file to make it run every day, every hour or whatever.  At least that's my understanding of it.  If you guys can tell me how to do that or at least point me in the right direction (step by step not necessary unless that's just your thing)  :)  that'd be great, otherwise when I figure it out I'll reopen the issue and report back what I did so other folks might find it here.  Thanks Juan!

**Comment by juan131** [comment]
Hi @pdcatbsc 

First of all, thanks so much for your great feedback about the README(s) and the assumptions we did without properly documenting them. I agree there is room for improvement to document the differences between our VMs and our containers. I'll share your feedback with the docs team so they can evaluate it, thanks again.

Regarding plugin installation, I opened an issue some time ago (see https://github.com/bitnami/bitnami-docker-redmine/issues/118) because as you mentioned it's needed to install some gems for them to work. We don't have a solution for this (yet) but some users shared on that issue their workarounds to create their own Docker images including the plugins. Check for instance the last response by "dannidov" where he shared the Dockerfile used to install a custom plugin and them.

Finally, regarding cron jobs, `crontab` is not included in the image by default, see:

```console
$ docker run --rm -it bitnami/redmine:4 bash
# crontab
bash: crontab: command not found
```

You can create your custom Redmine image including it. For instance, using the Dockefile below:

```Dockerfile
FROM bitnami/redmine:4
RUN install_packages cron
```

```console
$ docker build . -t my-custom-redmine:4
```

Then, you can add your cron jobs:

```console
$ docker run --rm -it bitnami/redmine:4 bash
# crontab -e
```

**Comment by pdcatbsc** [comment]
That's how I've made progress, finding bits and pieces from people's postings, applying them to my configuration, evaluating the error messages and adjusting course.  You can check my homework and let me know if this is going to wreck something, but I finally got it working.  It's probably not the proper way to do things, but I didn't modify anything inside the container.  

I started with the bundle exec command someone posted.  I ran that inside the container and fiddled with it until I got it to work with my settings.  Took a while because I was using some old emails I had previously used until I read where the email has to be unread or it will be ignored.  I sent a couple new test messages and they worked. I marked a couple of the old ones as unread and they worked also. Also had to figure out the email from address had to be linked to an authorized redmine user or it would be ignored.  Once I got it working in the container, I had to figure out how to use the docker exec command to make it work from outside the container.  It was bombing out with the -it switch and I read you could over-ride the TTY error msg with the -T switch.  That gave me a different error (I forget what) but when I got rid of all of that, it worked.  I'm still a bit fuzzy on the interactive input/output thing, but I'll worry about that later.  :)  

And the crontab part is just my local system.  I just run the following command from my local crontab and it works ok:
 
*/30 * * * * docker exec -w /opt/bitnami/redmine software_redmine_1 /bin/bash -c “bundle exec rake -f /opt/bitnami/redmine/Rakefile redmine:email:receive_imap RAILS_ENV=”production” host=outlook.office365.com port=993 ssl=true username=user@outlook.com password=password allow_override=all project=new-tasks unknown_user=accept folder=Inbox move_on_success=Read”

I'm sure there's a lot easier way to do this, but I've never been a "design it with a flow-chart before you start" kinda guy, I've always been a "beat my head against the wall until it's bloody" kinda guy, so it may be ugly, but it's working.  :)  I guess you can close this one out and I'll refer back to it when I get started on installing plugins.  I appreciate your help!

**Comment by pdcatbsc** [comment]
I guess that : email : thing is some kind of system variable or something, reason that doesn't print right. Supposed to be redmine(colon)email(colon)receive_imap for anyone not familiar with that option.  :)

**Comment by juan131** [comment]
Hi @pdcatbsc 

Thanks so much for sharing you experience and you solved it!

A couple of notes that might be helpful for you:

1) Containers are, by design, meant to be **ephemeral**. Therefore, if you install anything manually in the container by running `docker exec ...` and the container is recreated, you lose whatever you installed. This is the reason why I recommended you to create your own image if you want to install custom plugins, since this way your image contains them and you don't need to repeat these actions if the container is recreated.
2) Please read carefully the [Persistence section](https://github.com/bitnami/bitnami-docker-redmine#persisting-your-application) to understand how to use volume to ensure you don't lose any data in you Redmine container.

**Comment by pdcatbsc** [comment]
I understand.  I don't really understand volumes vs. bind mounts, but I read all that when I first started and had no clue how all this stuff interacted.  Don't know that I have much more of a clue now, but I'll go back and read it all again and maybe I'll grasp it better.  This is what I have in my docker-compose-postgresql.yml file:

services:
  postgresql:
  ...
    volumes:
      - '/home/user/bitnami/postgresql:/bitnami/postgresql'
  ...
  redmine:
  ...  
    volumes:
      - '/home/user/bitnami:/bitnami'
  ...

When the containers were first created, inside the bitnami folder a postgresql folder was created and inside that a data and _data folders were created.  A redmine folder was also created and conf, files, plugins and repository folders were created in there.  All the data resides in those folders.  Is that all you have to do for data persistence?  I just don't know if I'm ready to create my own image yet.  :smile:

**Comment by juan131** [comment]
Hi @pdcatbsc 

I recommend you using different directories for Redmine and PostgreSQL data so you don't mess up anything. For instance:

```yaml
services:
  postgresql:
  ...
    volumes:
      - '/home/user/bitnami/postgresql:/bitnami/postgresql'
  ...
  redmine:
  ...  
    volumes:
      - '/home/user/bitnami/redmine:/bitnami'
  ...
```

This way you'll have the Redmine data (Apache + Redmine data) at `/home/user/bitnami/redmine`, and PostgreSQL data at `/home/user/bitnami/postgresql`.

**Comment by pdcatbsc** [comment]
That's what I have.  They are in two separate locations.  When I first set it up I can't remember if I used '/home/user/bitnami/redmine:/bitnami' or what, but it put the data in the /home/user/bitnami/redmine/redmine directory.  So I changed it back to how I have it above and it put the redmine data in the /home/user/bitnami/redmine directory and the postgresql data in the /home/user/bitnami/postgresql directory.  I tested out the draw.io plugin yesterday and it worked without a hitch.  All I did was go to the plugins directory on the redmine persisted volume, used the git clone command for that plugin and it copied it down into the redmine_drawio directory.  I restarted the redmine container and drawio was there.  I didn't have to run a migration or anything it was all handled internally to the container.  So I guess since those volumes are persisted, if I lost that container, once a new redmine container comes up and looks in that plugin directory, it would automatically migrate the plugin back into redmine, so looks like I'm good to go for now.  So far I haven't edited or added anything to the container at all, it's just like it was when I downloaded it from Bitnami other than the config changes I've made inside the redmine app itself.  :)

**Comment by juan131** [comment]
> So I changed it back to how I have it above and it put the redmine data in the /home/user/bitnami/redmine directory and the postgresql data in the /home/user/bitnami/postgresql directory.

Perfect! 

> So I guess since those volumes are persisted, if I lost that container, once a new redmine container comes up and looks in that plugin directory, it would automatically migrate the plugin back into redmine, so looks like I'm good to go for now.

Correct, this Redmine container is design to reuse existing data when detected instead of configuring Redmine from scratch every time the container is recreated/restarted.

> I tested out the draw.io plugin yesterday and it worked without a hitch. All I did was go to the plugins directory on the redmine persisted volume, used the git clone command for that plugin and it copied it down into the redmine_drawio directory. I restarted the redmine container and drawio was there. I didn't have to run a migration or anything it was all handled internally to the container.

Great!! I am very glad you could get it working!

Please do not hesitate to let us know if you require any further help.
