### ISSUE TITLE
Option to change user to runAsNonRoot

### ISSUE THREAD

**Issue by JustasStankunas** [bitnami/bitnami-docker-redmine#156]
Currently latest version (4.1.1) image is set to be running with `root` privileges and it does not look that there is a way around it (even the script creating bitnami user by default adds it to passwordless sudoers..). are there any plans to move away from root based configuration?

**Comment by juan131** [comment]
Hi @JustasStankunas 

We already moved every infrastructure image to the "non-root" approach, and we also did the same on several web apps such as WordPress, Joomla! Ghost or Drupal. We plan to do the same with the rest of web apps that doesn't follow this approach yet such as Redmine. 

I am afraid I can provide you any ETA, but I can tell you that it is in our roadmap in the mid-term.
