### ISSUE TITLE
Unable export gantt chart as image type

### ISSUE THREAD

**Issue by tienthanh2509** [bitnami/bitnami-docker-redmine#158]
**Description**

Redmine docker image is missing font `helvetica` therefore unable export gantt chart as image

**Steps to reproduce the issue:**

Redmine image tag: `bitnami/redmine:4-debian-10`

1. Go to gantt chart section
2. Go to the bottom of page
3. Click `Also available in: PDF | PNG` click PNG

**Describe the results you received:**

Error 500

```
/mini_magick20201028-121-1s2elbc.png` failed with error:
redmine_1  | convert-im6.q16: unable to read font `helvetica' @ error/annotate.c/RenderFreetype/1338.
redmine_1  | convert-im6.q16: non-conforming drawing primitive definition `text' @ error/draw.c/RenderMVGContent/4301.

```

Can workaround by install add `contrib` archive and run `install_packages ttf-mscorefonts-installer`

Ref: https://packages.debian.org/search?keywords=ttf-mscorefonts-installer

Please help check
Thanks

**Comment by rafariossaa** [comment]
Hi,
  We can not include that package due to package lincense, however, I have tried installing `gsfonts` and it worked.
  We are working to make a new release that include that package. 
  I will come back as soon as I have news. It shouldn't take long as it is currently in our CI/CD.

**Comment by rafariossaa** [comment]
Hi,
  Could you give a try to the lastest release (4.1.1-debian-10-r168) ?

**Comment by tienthanh2509** [comment]
@rafariossaa Thanks, the new version worked, but the font only supports Latin characters

![image](https://user-images.githubusercontent.com/1713444/98002838-96a34000-1e20-11eb-86e6-aff2e79d8363.png)

Anyway, this ticket is close since Redmine can render image for Gantt chart

**Comment by rafariossaa** [comment]
Hi,
  I think it would work because `gsfonts` contains a configuration file for ghostscript where the fonts are mapped to the corresponding file.
