### ISSUE TITLE
Gmail SMTP not working

### ISSUE THREAD

**Issue by rokokorn** [bitnami/bitnami-docker-redmine#159]
I am using docker-compose for bitnami redmine stack.
mariadb: image: 'docker.io/bitnami/mariadb:10.3-debian-10'
redmine: image: 'docker.io/bitnami/redmine:4'

I tried to set up gmail smtp with
      - SMTP_HOST=smtp-relay.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=user@mydomain.com
      - SMTP_PASSWORD= "APP_specific_password"
      - SMTP_DOMAIN=mydomain.com
      - SMTP_TLS=true
      - SMTP_AUTHENTICATION=login

When running redmine docker, in the redmine UI  I want to send user credentials but it just says - setting updated. When checking logs there is error:
[ActiveJob] [ActionMailer::DeliveryJob] [ca5bd61b-fd8a-43d2-9920-02f1e4a43b4b] Email delivery error: 534-5.7.9 Application-specific password required. 

Mail is not sent.

**Version**

- Output of `docker version`:

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:52 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 3
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-52-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 981.3MiB
 Name: docker-s-1vcpu-1gb-fra1-01
 ID: YVPQ:U62Z:WQXU:FNCP:HLHI:GDT5:Z3BR:7POI:NN7S:YF4E:JYKZ:3IRZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

Running 
Linux docker-s-1vcpu-1gb-fra1-01 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

on digitalOcean.

**Comment by miguelaeh** [comment]
Hi @rokokorn .
Which are the steps you are following? We test the STMP scenario in every release so it should be working fine. I just checked in our CI/CD and the test are passed successfully.

**Comment by rokokorn** [comment]
@miguelaeh 

As said above, I tried to setup gmail smtp in the docker-compose.yml.
For the gmail itself i'm using gSuite account with 2SV. For mail with RM i setup app password (https://support.google.com/accounts/answer/185833?hl=en-GB) and smtp relay (https://support.google.com/a/answer/2956491).

Any other suggestions?

thanks

**Comment by miguelaeh** [comment]
Hi @rokokorn ,
I am afraid I am not sure about why this is falining. Searching for similar issues I found it appears when:
- You are using 2SV in the account (which seems to be your case), in this case, this is solved using App Passwords (you are using them).
- When that still not works, the following google docs:
```
If you use a non-Google app and can't sign in, the app's sign-in process might not be secure. Try to update to the latest version of the app and use "Sign in with Google," if it’s an option.
```
Have you tried to enable access for non-secure apps in your account configuration?

**Comment by rokokorn** [comment]
I didn't tried yet since I would need to disable 2SV first. This is not a desired option, but I will try it. Do you use less secure option in your tests?

**Comment by miguelaeh** [comment]
Hi @rokokorn ,
We don't use Gmail in our test. But I have configured sometimes STMP using Gmail and I remember I needed to do that to make it work.
But, to be honest, I have never done it using 2SV.

**Comment by rokokorn** [comment]
I used less secure apps and it is working. But I created another user for this, which costs me money.
However, if there are some changes you will make to configuration to support 2SV it would be awesome.

**Comment by miguelaeh** [comment]
Hi @rokokorn ,
I will create an internal task to check that on our side.
Thank you for sharing it

**Comment by beltran-rubo** [comment]
Hi @rokokorn, We use GMail just as an example for SMTP but it has several limitations. If you want to use this application in production and send multiple emails I would suggest to use a different external SMTP service. It is not possible to use SMTP with GMail with 2SV with any web application.
