### ISSUE TITLE
Redmine Themes disappearing after reboot

### ISSUE THREAD

**Issue by max1e6** [bitnami/bitnami-docker-redmine#161]
Custom themes disappear after restarting docker container.

I installed a custom theme in /opt/bitnami/redmine/public/themes and after issuing a docker-compose down and later docker-compose up redmine reverted to default theme, which makes sense because that is what redmine does if custom theme is missing.

I was able to fix this by adding an additional volume to my docker-compose.yml file:

      - './data_themes:/opt/bitnami/redmine/public/themes'

and this works and I was wondering if there was an "official" way to do this.

I noticed that there are symbolic links in /opt/bitnami/redmine for config, files, logs and plugins to corresponding directories in /bitnami/redmine but not for public.

If there were a similar symbolic link for public then the second volume I created would not be necessary.

**Comment by max1e6** [comment]
I was able to fix the issue by persisting the volume and I totally get why you are not doing this...It did not occur to me that doing so would cause an issue if the default themes were updated.

Would it make sense to add a script at boot to copy files from a directory outside the container to a directory inside the container?

For example, one could have a themes directory on the docker host that would get copies to the containers themes directory on boot this would both enable default themes to be kept up to date while also allowing for custom themes to be preserved.

Max.

**Comment by migruiz4** [comment]
As of now, the Redmine persisted paths are configured during this step:

https://github.com/bitnami/bitnami-docker-redmine/blob/cc94500fbe258c2f5e15797eaec77739a2fc72b5/4/debian-10/Dockerfile#L16

The logic inside that package is not public and can not be easily modified, but we have plans to migrate that logic to a public bash logic as we did with other applications:
- https://github.com/bitnami/bitnami-docker-moodle/blob/master/3/debian-10/Dockerfile
- https://github.com/bitnami/bitnami-docker-joomla/blob/master/3/debian-10/Dockerfile

Until then we can not provide an official solution to support custom themes and it would be necessary to mount the themes as volumes.
```
  - './custom_theme:/opt/bitnami/redmine/public/themes/my_custom_theme'
```

Or building a custom image to add the additional themes in case you don't want to rely on the Docker host storage:
```Dockerfile
FROM docker.io/bitnami/redmine:4.1.1-debian-10-r268
WORKDIR /opt/bitnami/redmine/
COPY themes/ /opt/bitnami/redmine/public/themes
RUN chown 1001:1001 . -R
```

Regarding your question:
> Would it make sense to add a script at boot to copy files from a directory outside the container to a directory inside the container?
> 
> For example, one could have a themes directory on the Docker host that would get copies to the containers themes directory on boot this would both enable default themes to be kept up to date while also allowing for custom themes to be preserved.

This method would be similar to mounting the themes as volumes, but not having to use individual volumes for every theme.

I think the container should persist `/opt/bitnami/redmine/public/themes` inside `redime_data`, but when upgrading the image it should overwrite the default themes existing in the volume with the new ones.

But again, this feature will have to wait until the current package is replaced with the bash logic.
