### ISSUE TITLE
SSL configuration

### ISSUE THREAD

**Issue by mr-keane** [bitnami/bitnami-docker-redmine#165]
I'm looking for a way to make the redmine site SSL only. I saw you mentioned we cannot use the VM guides. Is there a way to configure a redirect from HTTP and provide certs we have for our domain?

**Comment by carrodher** [comment]
Using the container standalone I am not sure if this can be configured, probably for this kind of advanced options, you will need to deploy Redmine using the Helm Chart.

The chart can be found [here](https://github.com/bitnami/charts/tree/master/bitnami/redmine), and there are some sections in the README about certificates, ingress, TLS, etc, for example, https://github.com/bitnami/charts/tree/master/bitnami/redmine#certificates or https://github.com/bitnami/charts/tree/master/bitnami/redmine#exposure-parameters

See for example this doc about how to configure the ingress: https://docs.bitnami.com/kubernetes/apps/redmine/configuration/configure-ingress/
