### ISSUE TITLE
Email Setting Error: An error occurred while sending mail (end of file reached)

### ISSUE THREAD

**Issue by rang0419** [bitnami/bitnami-docker-redmine#166]
**Description**

**Steps to reproduce the issue:**

1. [First Step]

my email config 
\bitnami\redmine\conf\configuration.yml

#default:
production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: "smtp.qq.com" 
      port: 465
      domain: "qq.com" 
      authentication: :plain
      user_name: "1291800000" 
      password: "xxxxxxxxx"

2. [Second Step]

Administration\settings\Email notifications\ Send a test email

3. [and so on...]

**Describe the results you received:**+

An error occurred while sending mail (end of file reached)
https://imgur.com/tKIcFbn

**Describe the results you expected:**

Emil service can be used normally

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

- Output of `docker info`:

```
(paste your output here)
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 4
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.29GiB
 Name: docker-desktop
 ID: IJGH:HTPN:PB6V:N3D5:BMYI:7GGW:DVWM:PBK7:7ROU:GI24:ZX3A:5QWT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by marcosbc** [comment]
Hi @rang0419, did you deploy the container image using the [supported environment variables for SMTP configuration](https://github.com/bitnami/bitnami-docker-redmine#smtp-configuration)? Note that the internal logic relies on these to make any appropriate change to the configuration, which may be more than just modifying the YAML file.

If you did, could you share how you deployed your Redmine instance? (with configuration parameters if possible)

**Comment by rang0419** [comment]
> Note that the internal logic relies on these to make any appropriate change to the configuration, which may be more than just modifying the YAML file.


I am directly modifying configuration.yml
\opt\bitnami\redmine\conf\ configuration.yml

Qusetion1:
Only modify docker-compose.yml?
Or do both docker-compose.yml & configuration.yml need to be modified?

Modify the docker-compose.yml file present in this repository:
   redmine:
   ...
     environment:
       -SMTP_HOST=smtp.gmail.com
       -SMTP_PORT=587
       -SMTP_USER=your_email@gmail.com
       -SMTP_PASSWORD=your_password

Qusetion2:
If I compose-up for the first time, [without adding redmine:
environment:], how do I modify it to be correct after the second time?

Thanks!

**Comment by rang0419** [comment]
> Hi @rang0419, did you deploy the container image using the [supported environment variables for SMTP configuration](https://github.com/bitnami/bitnami-docker-redmine#smtp-configuration)? Note that the internal logic relies on these to make any appropriate change to the configuration, which may be more than just modifying the YAML file.
> 
> If you did, could you share how you deployed your Redmine instance? (with configuration parameters if possible)

I have used environment variables and still get the same error message.
An error occurred while sending mail (end of file reached)

  redmine:
    image: docker.io/bitnami/redmine:4
#    改密碼後須先啟用，然後至/bitnami/redmine/conf/database.yml新增密碼
#    command: sleep infinity
    environment:
      - REDMINE_DB_USERNAME=bn_redmine
      - REDMINE_DB_PASSWORD=
      - REDMINE_DB_NAME=bitnami_redmine
      - REDMINE_USERNAME=admin
      - REDMINE_PASSWORD=admin
      - REDMINE_LANGUAGE=zh 
      - SMTP_HOST=smtp.qq.com
      - SMTP_PORT=465
      - SMTP_USER=12918xxxxx@qq.com
      - SMTP_PASSWORD=mnypassword

**Comment by rang0419** [comment]
Hi~~~ I got it
The problem lies in the difference between "abc" and no abc

The correct version is:

production:
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      enable_starttls_auto: true
      address: smtp.qq.com
      port: 587
      domain: "smtp.qq.com"
      authentication: :plain
      user_name: "12918wwwww@qq.com" 
      password: sdssssssssssssss

**Comment by rang0419** [comment]
Thx for your help!
