### ISSUE TITLE
[Feature request] add `rest_api_enabed` via an env var during deployment

### ISSUE THREAD

**Issue by Gleland** [bitnami/bitnami-docker-redmine#170]
Feature Request

Redmine supports [REST API](https://www.redmine.org/projects/redmine/wiki/Rest_api) calls for various project administration. However, in order for a user to enable this, they must first go into the Administration settings to check the `Enable Rest API` box. Would it be possible to add a config option to enable this at deployment time? Here's the code where the default is set:

https://github.com/redmine/redmine/blob/805b36cbfbb0291f4aa4dfaa009bb088386749a9/config/settings.yml#L311-L312

Thanks for your time!

**Comment by javsalgar** [comment]
Hi,

Thank you so much for the feedback. I will create a task for this. However, if you want to speed up the process, we accept contributions in the form of PRs. All the code is in bash libraries like this https://github.com/bitnami/bitnami-docker-redmine/blob/master/4/debian-10/rootfs/opt/bitnami/scripts/libredmine.sh

Would you like to contribute with a PR? If not, we will work on it.

**Comment by Gleland** [comment]
sure thing! I just tried it out, please let me know if there are any issues/concerns.

**Comment by yilmi** [comment]
Thanks @Gleland for the PR, I'll do my best to get back to you quickly! 👍

**Comment by javsalgar** [comment]
as the PR is merged, this issue could be closed
