### ISSUE TITLE
No upload possible 1 MB or more, REDMINE_SMTP variables not working. 

### ISSUE THREAD

**Issue by creactiv** [bitnami/bitnami-docker-redmine#174]
Well, 
this is just about a setting within Redmine. 

in config/settings.yml i find this: 

![grafik](https://user-images.githubusercontent.com/6092608/143038712-b84d98dd-6c8f-42dc-99d8-d386b1bdfeb0.png)

and am wondering, what this 5120 is about. 5 kB, 5MB? 
 
Whenever i want to upload a file which is around 1 MB or more, it goes with File invalid Request Entity Too (large i suppose)

I CAN change the upload file size limit, but it won't be respected. So how can i get around this?

And another thing i am wondering about. When i am using in my docker-compose.yml the REDMINE_SMTP settings, shouldn't Redmine itself recognize them? In Configuration it still says in the email tab, that email setup hasn't been done yet. 

Thanks for pointing me in the right direction. 

Best

**Comment by creactiv** [comment]
Hi,
Thanks for getting back. So it should utilize 5 MB files but it claims 1 MB files as invalid and file too long. I also set the max file upload size to 50 MB, which wouldn't wor either.


So there might be another setting.

We are talking about a docker'ed installation and as soon, as i restart, my settings in the container have gone, as intended. So basically i am looking into how to get rid of this upload error and to get email working.

Thanks for help and best

Von: Rafael Ríos Saavedra ***@***.***>
Gesendet: Mittwoch, 24. November 2021 10:01:21
An: bitnami/bitnami-docker-redmine
Cc: Holger Schramm; Author
Betreff: Re: [bitnami/bitnami-docker-redmine] No upload possible 1 MB or more, REDMINE_SMTP variables not working. (Issue #174)
 



Hi,

and am wondering, what this 5120 is about. 5 kB, 5MB?

Could you take a look to this 
link ?

And another thing i am wondering about. When i am using in my docker-compose.yml the REDMINE_SMTP settings, shouldn't Redmine itself recognize them? In Configuration it still says in the email tab, that email setup hasn't been done yet.

Could you try using this docker-compose file ?
$ cat docker-compose.yml 
version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.4
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_redmine
      - MARIADB_DATABASE=bitnami_redmine
  redmine:
    image: docker.io/bitnami/redmine:4
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=bn_redmine
      - REDMINE_DATABASE_NAME=bitnami_redmine
      - REDMINE_SMTP_HOST=smtp.gmail.com
      - REDMINE_SMTP_PORT=587
      - ***@***.***
      - REDMINE_SMTP_PASSWORD=your_password
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local

When I use it I can see the configuration is set in:

$ cat /opt/bitnami/redmine/config/configuration.yml
...
default:
  # Outgoing emails configuration
  # See the examples below and the Rails guide for more configuration options:
  # http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
  email_delivery:
    delivery_method: :smtp
    smtp_settings:
      address: smtp.gmail.com
      port: "587"
      authentication: login
      user_name: ***@***.***
      password: your_password
      domain: gmail.com
      enable_starttls_auto: "false"
...

Could you check that ?
I am not very sure where you are getting that the email setup hasn't been done yet.
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
Triage notifications on the go with GitHub Mobile for 
iOS or 
Android. 
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/bitnami/bitnami-docker-redmine/issues/174#issuecomment-977670145",
"url": "https://github.com/bitnami/bitnami-docker-redmine/issues/174#issuecomment-977670145",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rafariossaa** [comment]
> Hi, Thanks for getting back.
 So it should utilize 5 MB files but it claims 1 MB files as invalid and file too long. I also set the max file upload size to 50 MB, which wouldn't wor either. 
So there might be another setting. 

Maybe you can consider asking this question in redmine's forums.

> We are talking about a docker'ed installation and as soon, as i restart, my settings in the container have gone, as intended. So basically i am looking into how to get rid of this upload error and to get email working.

Could you provide step by step what are you doing and which settings you get removed ?, sometimes this hide in little details when operating.

**Comment by creactiv** [comment]
Well, i would need to change that variable. On a standard onPremise installation, this would be a piece of cake, within this dockerized environment i am not sure, where to change what without breaking everything.

Thanks and best

**Comment by rafariossaa** [comment]
Hi,  
  The current logic in the container doesn't support changing that parameter, but you can put an script in `/docker-entrypoint-init.d` to do the changes you need, and it  would be execute in [`post-init` stage](https://github.com/bitnami/bitnami-docker-redmine/blob/master/4/debian-10/rootfs/post-init.sh).
