### ISSUE TITLE
Email delivery error: 501 mail from address must be same as authorization user

### ISSUE THREAD

**Issue by fcmxmk** [bitnami/bitnami-docker-redmine#178]
It is not possible to modify the `mail_from` parameters in `/opt/bitnami/redmine/config/settings.yml` during construction, this will cause a `501` error: 

```
Email delivery error: 501 mail from address must be same as authorization user
```

unless you log in to the background and manually modify the `mail_from`

**Comment by carrodher** [comment]
Please, [note the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
