### ISSUE TITLE
notice email could not be sent

### ISSUE THREAD

**Issue by kt1024** [bitnami/bitnami-docker-redmine#181]
### Name and Version

bitnami/redmine:4.2.5

### What steps will reproduce the bug?

1. try 4.2.5 first , then upgrade to 5.0.0. both failed.
2. send test mail in "setting" success, also changing user email address can receive notice mail.
3. crate an issue and assign issue/ update issue. 
4. no email was received/ or sent to mail server.

smtp parameter:
<pre>
  -e REDMINE_SMTP_HOST=smtp2.corp.server \
  -e REDMINE_SMTP_PORT=587 \
  -e REDMINE_SMTP_USER=redmine-service@corp.server \
  -e REDMINE_SMTP_PASSWORD=email-pass \
  -e REDMINE_SMTP_PROTOCOL=tls \
</pre>

### What is the expected behavior?

user can receive notify email.

### What do you see instead?

logs when update an issue:
<pre>
I, [2022-04-27T08:06:35.869497 #227]  INFO -- : [a925ee89-ed6b-44fb-89f7-5e841dfeb791] Started GET "/issues/1?issue_count=1&issue_position=1" for 172.16.8.1 at 2022-04-27 08:06:35 +0000
I, [2022-04-27T08:06:35.873285 #227]  INFO -- : [a925ee89-ed6b-44fb-89f7-5e841dfeb791] Processing by IssuesController#show as HTML
I, [2022-04-27T08:06:35.873864 #227]  INFO -- : [a925ee89-ed6b-44fb-89f7-5e841dfeb791]   Parameters: {"issue_count"=>"1", "issue_position"=>"1", "id"=>"1"}
I, [2022-04-27T08:06:35.920580 #227]  INFO -- : [a925ee89-ed6b-44fb-89f7-5e841dfeb791]   Current user: user (id=1)
I, [2022-04-27T08:06:35.983234 #227]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [9bed6afb-84c3-4a29-b7d0-fe76e833a146]   Rendered mailer/issue_edit.text.erb within layouts/mailer (Duration: 71.3ms | Allocations: 3643)
I, [2022-04-27T08:06:35.984820 #227]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [9bed6afb-84c3-4a29-b7d0-fe76e833a146]   Rendered layout layouts/mailer.text.erb (Duration: 73.0ms | Allocations: 3689)
I, [2022-04-27T08:06:36.007733 #227]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [9bed6afb-84c3-4a29-b7d0-fe76e833a146]   Rendered mailer/issue_edit.html.erb within layouts/mailer (Duration: 20.1ms | Allocations: 1261)
I, [2022-04-27T08:06:36.010606 #227]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [9bed6afb-84c3-4a29-b7d0-fe76e833a146]   Rendered layout layouts/mailer.html.erb (Duration: 23.1ms | Allocations: 1520)
I, [2022-04-27T08:06:36.060848 #227]  INFO -- : [ActiveJob] [ActionMailer::MailDeliveryJob] [9bed6afb-84c3-4a29-b7d0-fe76e833a146] Performed ActionMailer::MailDeliveryJob (Job ID: 9bed6afb-84c3-4a29-b7d0-fe76e833a146) from Async(mailers) in 241.48ms
I, [2022-04-27T08:06:36.700069 #227]  INFO -- : [a925ee89-ed6b-44fb-89f7-5e841dfeb791]   Rendered issues/show.html.erb within layouts/base (Duration: 439.3ms | Allocations: 28315)
I, [2022-04-27T08:06:36.826023 #227]  INFO -- : [a925ee89-ed6b-44fb-89f7-5e841dfeb791]   Rendered layout layouts/base.html.erb (Duration: 565.4ms | Allocations: 36155)
I, [2022-04-27T08:06:36.828056 #227]  INFO -- : [a925ee89-ed6b-44fb-89f7-5e841dfeb791] Completed 200 OK in 953ms (Views: 517.3ms | ActiveRecord: 211.8ms | Allocations: 61243)
</pre>

**Comment by carrodher** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.

If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.

**Comment by kt1024** [comment]
dead loop
![image](https://user-images.githubusercontent.com/12657496/165482151-76c06480-ff71-4cbd-8bcb-6480e1bef166.png)
