### ISSUE TITLE
does not work with folders as volumes in windows

### ISSUE THREAD

**Issue by andresgarcia0313** [bitnami/bitnami-docker-redmine#182]
### Name and Version

bitnami/redmine

### What steps will reproduce the bug?

# In this enviroment
Windows 11 Home
# with this config

version: '2'
services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    volumes:
      - './db:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=gestor
      - MARIADB_DATABASE=projectdb
    restart: always
  redmine:
    image: docker.io/bitnami/redmine:5
    ports:
      - '80:3000'
    volumes:
      - './app:/bitnami/redmine'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development. - REDMINE_PASSWORD=asde7104
      - ALLOW_EMPTY_PASSWORD=yes
      - REDMINE_DATABASE_HOST=mariadb
      - REDMINE_DATABASE_PORT_NUMBER=3306
      - REDMINE_DATABASE_USER=gestor
      - REDMINE_DATABASE_NAME=projectdb
# Run '...'
docker-compose up
# See error

### What is the expected behavior?

What is the expected behavior?
If possible please provide textual output instead of screenshots.

The redmine container does not finish starting, it shows that it is migrating but it does not work

### What do you see instead?

redmine 15:42:10.93 

redmine 15:42:10.93 Welcome to the Bitnami redmine container

redmine 15:42:10.93 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine

redmine 15:42:10.93 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues

redmine 15:42:10.93 

redmine 15:42:10.96 INFO  ==> Validating settings in MYSQL_CLIENT_* env vars

redmine 15:42:10.98 INFO  ==> Validating settings in POSTGRESQL_CLIENT_* env vars

redmine 15:42:11.03 WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.

redmine 15:42:11.04 INFO  ==> Ensuring Redmine directories exist

redmine 15:42:11.06 INFO  ==> Trying to connect to the database server

redmine 15:42:31.20 INFO  ==> Configuring Redmine database connections

redmine 15:42:31.27 INFO  ==> Configuring Redmine application with settings provided via environment variables

redmine 15:42:31.29 INFO  ==> Executing database migrations

### Additional information

Additional Information
Tell us anything else you think we should know.
It doesn't seem to finish the migrations.

When I do it with docker volumes it works perfectly

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
