### ISSUE TITLE
Issue running bundle in container

### ISSUE THREAD

**Issue by wthsia** [bitnami/bitnami-docker-redmine#183]
### Name and Version

bitnami\redmine5

### What steps will reproduce the bug?

In redmine docker run:

docker exec -i redmine /opt/bitnami/redmine/bin/bundle exec /opt/bitnami/redmine/bin/rake -f /opt/bitnami/redmine/Rakefile redmine:email:receive_imap port=993  RAILS_ENV="production" host=MAILSERVER username=USER password=PASSWORD!  ssl=1 project=test tracker=Support unknown_user=create --trace

### What is the expected behavior?

create issue via email

### What do you see instead?

Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.
** Invoke redmine:email:receive_imap (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute redmine:email:receive_imap
rake aborted!
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate)
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:46:in `connect_nonblock'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/net-protocol-0.1.3/lib/net/protocol.rb:46:in `ssl_socket_connect'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/net-imap-0.2.3/lib/net/imap.rb:1452:in `start_tls_session'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/net-imap-0.2.3/lib/net/imap.rb:1107:in `initialize'
/opt/bitnami/redmine/lib/redmine/imap.rb:32:in `new'
/opt/bitnami/redmine/lib/redmine/imap.rb:32:in `check'
/opt/bitnami/redmine/lib/tasks/email.rake:121:in `block (4 levels) in <top (required)>'
/opt/bitnami/redmine/app/models/mailer.rb:648:in `with_synched_deliveries'
/opt/bitnami/redmine/lib/tasks/email.rake:120:in `block (3 levels) in <top (required)>'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `synchronize'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:83:in `block in run'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/lib/rake/application.rb:80:in `run'
/opt/bitnami/redmine/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/opt/bitnami/redmine/bin/rake:27:in `load'
/opt/bitnami/redmine/bin/rake:27:in `<top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `load'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli/exec.rb:23:in `run'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli.rb:483:in `exec'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli.rb:31:in `dispatch'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/cli.rb:25:in `start'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/exe/bundle:48:in `block in <top (required)>'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/opt/bitnami/ruby/lib/ruby/gems/3.0.0/gems/bundler-2.3.11/exe/bundle:36:in `<top (required)>'
/opt/bitnami/redmine/bin/bundle:113:in `load'
/opt/bitnami/redmine/bin/bundle:113:in `<main>'
Tasks: TOP => redmine:email:receive_imap

**Comment by rafariossaa** [comment]
Please, [note that the Bitnami team is not actively monitoring GitHub Issues for this project](https://github.com/bitnami/bitnami-docker-redmine#community-supported-solution). This issue will stay open for 20 days to allow the community to contribute, after 15 days without activity the issue will be marked as stale, being closed after 5 days.
If you would like to contribute to this container image by fixing a bug or adding a new feature, feel free to create a PR, the Bitnami team will be happy to review it and provide feedback.
