### ISSUE TITLE
how to configure sub-uri after version 4.2.1-r70

### ISSUE THREAD

**Issue by leim** [bitnami/bitnami-docker-redmine#184]
### Name and Version

bitnami/redmine:4.2.1-debian-10-r69

### What is the problem this feature will solve?

version 4.2.1-r69 readme file, this was a comment tells how to use sub uri ,but this was remove since 4.2.1-r70, and this method fails after upgrade to version r70, i am wondering if there is any solution.

![微信截图_20220607234749](https://user-images.githubusercontent.com/1665397/172425117-cc0aad17-1b98-445b-b0fa-7e2da1dfb086.png)

![微信截图_20220607234810](https://user-images.githubusercontent.com/1665397/172425151-e3c29090-c51a-4f31-8a57-e4409ea04487.png)

### What is the feature you are proposing to solve the problem?

use sub uri path

**Comment by FraPazGal** [comment]
Hello @leim,

Thanks for bringing this up. It seems this was removed when we migrated to an updated initialization logic and hasn't been supported for quite some time. Even though it is not on our roadmap at the moment, we would be happy to review your PR in case you want to contribute with its configuration guide. You should be able to set it up following the [official documentation](https://www.redmine.org/projects/redmine/wiki/HowTo_Install_Redmine_in_a_sub-URI). 

For now, we will leave this ticket open in case more users can help with this or are interested in contributing with a PR.
