### ISSUE TITLE
Unable to get subversion to work

### ISSUE THREAD

**Issue by takamara** [bitnami/bitnami-docker-redmine#20]
So I managed to migrate my old 2.6 install in a standard bitnami installer over to the latest docker release here, and everything is working a treat except for repository access. Looking through the settings page it appeared that no SCM programs were installed in the container, so I went in and apt-get installed subversion. After setting the binary location in the config file, Redmine was still not finding it. I tried just running the executable in a bash shell within the container and it does run but it is throwing the following two errors

`svn: /usr/local/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libserf-1.so.1)`
`svn: /usr/local/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libserf-1.so.1)
`

before the output from subversion, which I'm guessing is messing with Redmine being able to parse the output. It seems that the image is shipping with libraries in /usr/local/lib that are different to those in the repositories, causing the error from libserf. I did try temporarily removing the two libraries in /usr/local/lib, which allowed svn to run without error but unfortunately caused passenger to crash when starting up the server. Is there perhaps a workaround for this where I might be able to get svn to use the system libraries but leave Redmine using the provided libraries?

**Comment by takamara** [comment]
I managed to find that I could get rid of the errors by executing svn as follows

`LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/ svn`

So finding this, I tried to put that in the subversion path in the configuration.yml file but Redmine fails to pick it up. Thinking that maybe it just wanted an executable name there, I wrote a little bash script

`#!/bin/bash`
`LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/ /usr/bin/svn "$@"``

and saved it as /usr/local/bin/svn, put that path as the svn executable name in the config file and it still fails to pick up the executable. I'm not really sure how else to do it as both methods allow svn to run flawlessly, but Redmine seems unable to use them. Unless you can advise of an svn version which is compatiible with the supplied libraries? But even then that might be problematic if it's too old a version as it wouldn't be compatible with the repo.

**Comment by sameersbn** [comment]
@takamara can you try renaming the `svn` binary to `svn.orig` (`mv /usr/bin/svn /usr/bin/svn.orig`) and installing your wrapper at `/usr/bin/svn` with the following content:

```bash
#!/bin/bash
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu
/usr/bin/svn.orig "$@"`
```

**Comment by takamara** [comment]
OK, so after a little more digging have finally fixed the issue. Having read through the production.log it seems the wrapper did fix the issue with libraries but it was coming across another error:

```
App 86 stderr: svn: warning: W000013: Can't open file '/root/.subversion/servers': Permission denied
App 86 stderr: /usr/local/bin/svn: line 2:   145 Segmentation fault      (core dumped) LD_LIBRARY_PATH=/lib/x86_64-linux-gnu/ /usr/bin/svn "$@"
```

I'm guessing that the server doesn't check the environment and so when it runs svn no home directory is available so it is defaulting to /root to look for the .subversion folder. Anyway if anyone else comes across the issue, do as @sameersbn mentioned above:

`mv /usr/bin/svn /usr/bin/svn.orig`

and then create the following file:

`/usr/bin/svn`

```
#!/bin/bash
export LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:/lib/x86_64-linux-gnu
/usr/bin/svn.orig --config-dir /home/redmine/.subversion "$@"
```

And finally make a subversion folder in the proper place:

`mkdir /home/redmine/.subversion`

The only change being to specify a config directory in the redmine user's home folder, thus avoiding the permissions issues. It's a bit hacky but it works :)

**Comment by prydonius** [comment]
Thanks @takamara! I'm going to re-open this so we can track the work on fixing this issue in the image for an upcoming release.

**Comment by juan131** [comment]
@takamara I tried to reproduce your issue on latest version of Bintami Redmine Docker Images and it seems solved. Could please confirm us that you're able to use subversion without using the wrapper? You shouldn't obtain the error below anymore:

```
svn: /usr/local/lib/libssl.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libserf-1.so.1)
svn: /usr/local/lib/libcrypto.so.1.0.0: no version information available (required by /usr/lib/x86_64-linux-gnu/libserf-1.so.1)
```

**Comment by sameersbn** [comment]
Yes, this issue should be resolved with newer bitnami/redmine images. Simply installing subversion from the debian package repositories should work. Closing issue.
