### ISSUE TITLE
exec user process caused "no such file or directory"

### ISSUE THREAD

**Issue by jedielson** [bitnami/bitnami-docker-redmine#22]
After build the image I've tried to run a new container, and I've received this message

**exec user process caused "no such file or directory"**

I'm running from an Windows 10, and I've not changed any file.

What can I do to run it?

**Comment by sameersbn** [comment]
@jedielson Are you using Docker Toolbox on Windows? or  Docker for Windows?

**Comment by sameersbn** [comment]
I just tried the [docker-compose.yml](https://github.com/bitnami/bitnami-docker-redmine/blob/master/docker-compose.yml) on Windows 10 and Docker Toolbox and didn't face the issue.

Could you please provide more details so that we can reproduce it?

**Comment by jedielson** [comment]
Hi.

Thanks for your help.
I'm using Docker for Windows!

**Comment by sameersbn** [comment]
@jedielson The issue could be due to the use of host volumes. If you're indeed using host volumes, then can you please try without them? 

It would be really helpful to us if you could share the command sequence of the `docker-compose.yml` that you're using. Additionally consider providing the information as listed in https://github.com/bitnami/bitnami-docker-redmine#issues

**Comment by jedielson** [comment]
Hi, Thanks for answering and sorry about other answers!
Here is my infos;

OS-> Microsoft Windows [version 10.0.10586]
Docker Version->
docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      windows/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 21:15:28 2016
 OS/Arch:      linux/amd64

Docker Info->
$ docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 13
Server Version: 1.12.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 16
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: overlay host bridge null
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 4.4.15-moby
Operating System: Alpine Linux v3.4
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.95 GiB
Name: moby
ID: UZNA:M4KS:4PEU:YWY2:VF3P:BNUT:AEN4:3Y3K:DTP5:N3CA:WWKB:XZ53
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8


Execution Log ->

jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine                                                                               
$ docker build -t redmine_jedi .                                                                                                                                         
Sending build context to Docker daemon 84.99 kB                                                                                                                          
Step 1 : FROM gcr.io/stacksmith-images/ubuntu:14.04-r8                                                                                                                   
14.04-r8: Pulling from stacksmith-images/ubuntu                                                                                                                          
                                                                                                                                                                         
56eb14001ceb: Pull complete                                                                                                                                              
7ff49c327d83: Pull complete                                                                                                                                              
6e532f87f96d: Pull complete                                                                                                                                              
3ce63537e70c: Pull complete                                                                                                                                              
df233bdf97ca: Pull complete                                                                                                                                              
38563b1c0b05: Pull complete                                                                                                                                              
525d5c144415: Pull complete                                                                                                                                              
205a8fe3e347: Pull complete                                                                                                                                              
Digest: sha256:c09df546f32dbaa926c000bd7d81744338eccde0d2aba473fa751f23b2b05899                                                                                          
Status: Downloaded newer image for gcr.io/stacksmith-images/ubuntu:14.04-r8                                                                                              
 ---> 65dfb2303799                                                                                                                                                       
Step 2 : MAINTAINER Bitnami <containers@bitnami.com>                                                                                                                     
 ---> Running in b8335278f50d                                                                                                                                            
 ---> cf618a5f4d68                                                                                                                                                       
Removing intermediate container b8335278f50d                                                                                                                             
Step 3 : ENV BITNAMI_APP_NAME redmine BITNAMI_IMAGE_VERSION 3.2.3-r1 PATH /opt/bitnami/ruby/bin:$PATH                                                                    
 ---> Running in 4298dd27b88f                                                                                                                                            
 ---> ed4d32fb7b09                                                                                                                                                       
Removing intermediate container 4298dd27b88f                                                                                                                             
Step 4 : RUN bitnami-pkg install ruby-2.1.9-2 --checksum d9a014bb284fe1bd181008aa7f78b70b5259a93014a175df0a7e42084b2e2dd4                                                
 ---> Running in 7417f7d0e4c9                                                                                                                                            
===> Downloading ruby-2.1.9-2-linux-x64 package                                                                                                                          
===> Verifying package integrity                                                                                                                                         
ruby-2.1.9-2-linux-x64.tar.gz: OK                                                                                                                                        
===> Installing ruby-2.1.9-2-linux-x64                                                                                                                                   
harpoon INFO  Installing /tmp/bitnami/pkg/install/ruby-2.1.9-2-linux-x64                                                                                                 
harpoon INFO  ruby successfully installed into /opt/bitnami/ruby                                                                                                         
 ---> 6f499343d2f0                                                                                                                                                       
Removing intermediate container 7417f7d0e4c9                                                                                                                             
Step 5 : RUN bitnami-pkg install imagemagick-6.7.5-10-3 --checksum 617e85a42c80f58c568f9bc7337e24c03e35cf4c7c22640407a7e1e16880cf88                                      
 ---> Running in f4950d0686a1                                                                                                                                            
===> Downloading imagemagick-6.7.5-10-3-linux-x64 package                                                                                                                
===> Verifying package integrity                                                                                                                                         
imagemagick-6.7.5-10-3-linux-x64.tar.gz: OK                                                                                                                              
===> Installing imagemagick-6.7.5-10-3-linux-x64                                                                                                                         
harpoon INFO  Installing /tmp/bitnami/pkg/install/imagemagick-6.7.5-10-3-linux-x64                                                                                       
harpoon INFO  imagemagick successfully installed into /opt/bitnami/common                                                                                                
 ---> 405c5d49b19f                                                                                                                                                       
Removing intermediate container f4950d0686a1                                                                                                                             
Step 6 : RUN bitnami-pkg install mysql-libraries-10.1.13-0 --checksum 71ca428b619901123493503f8a99ccfa588e5afddd26e0d503a32cca1bc2a389                                   
 ---> Running in 951072e5e19d                                                                                                                                            
===> Downloading mysql-libraries-10.1.13-0-linux-x64 package                                                                                                             
===> Verifying package integrity                                                                                                                                         
mysql-libraries-10.1.13-0-linux-x64.tar.gz: OK                                                                                                                           
===> Installing mysql-libraries-10.1.13-0-linux-x64                                                                                                                      
harpoon INFO  Installing /tmp/bitnami/pkg/install/mysql-libraries-10.1.13-0-linux-x64                                                                                    
harpoon INFO  mysql-libraries successfully installed into /opt/bitnami/common                                                                                            
 ---> 4586b3373530                                                                                                                                                       
Removing intermediate container 951072e5e19d                                                                                                                             
Step 7 : RUN bitnami-pkg install mysql-client-10.1.13-1 --checksum e16c0ace5cb779b486e52af83a56367f26af16a25b4ab92d8f4293f1bf307107                                      
 ---> Running in 4be664894392                                                                                                                                            
===> Downloading mysql-client-10.1.13-1-linux-x64 package                                                                                                                
===> Verifying package integrity                                                                                                                                         
mysql-client-10.1.13-1-linux-x64.tar.gz: OK                                                                                                                              
===> Installing mysql-client-10.1.13-1-linux-x64                                                                                                                         
harpoon INFO  Installing /tmp/bitnami/pkg/install/mysql-client-10.1.13-1-linux-x64                                                                                       
harpoon INFO  mysql-client successfully installed into /opt/bitnami/mysql                                                                                                
 ---> bcf5a81fd4c6                                                                                                                                                       
Removing intermediate container 4be664894392                                                                                                                             
Step 8 : RUN bitnami-pkg unpack redmine-3.3.0-0 --checksum 7635b0f9585ad8a950c632eff9220ef84a1c455e07c02418265cbada8a73f9ff                                              
 ---> Running in 0b9907fe9062                                                                                                                                            
===> Downloading redmine-3.3.0-0-linux-x64 package                                                                                                                       
===> Verifying package integrity                                                                                                                                         
redmine-3.3.0-0-linux-x64.tar.gz: OK                                                                                                                                     
===> Unpacking redmine-3.3.0-0-linux-x64                                                                                                                                 
harpoon INFO  Unpacking /tmp/bitnami/pkg/install/redmine-3.3.0-0-linux-x64                                                                                               
harpoon INFO  redmine successfully unpacked into /opt/bitnami/redmine                                                                                                    
 ---> aefcd7b92ad9                                                                                                                                                       
Removing intermediate container 0b9907fe9062                                                                                                                             
Step 9 : COPY rootfs /                                                                                                                                                   
 ---> b3168d2265e3                                                                                                                                                       
Removing intermediate container f64aee648ec1                                                                                                                             
Step 10 : VOLUME /bitnami/redmine                                                                                                                                        
 ---> Running in ff48074aafb9                                                                                                                                            
 ---> 093381148962                                                                                                                                                       
Removing intermediate container ff48074aafb9                                                                                                                             
Step 11 : EXPOSE 3000                                                                                                                                                    
 ---> Running in 5279678bb88d                                                                                                                                            
 ---> 9d98519fdbdb                                                                                                                                                       
Removing intermediate container 5279678bb88d                                                                                                                             
Step 12 : ENTRYPOINT /app-entrypoint.sh                                                                                                                                  
 ---> Running in 8df5a905ae1b                                                                                                                                            
 ---> eca05aba13a4                                                                                                                                                       
Removing intermediate container 8df5a905ae1b                                                                                                                             
Step 13 : CMD harpoon start --foreground redmine                                                                                                                         
 ---> Running in 948bc32e3a4f                                                                                                                                            
 ---> 8f4e8d8db64a                                                                                                                                                       
Removing intermediate container 948bc32e3a4f                                                                                                                             
Successfully built 8f4e8d8db64a                                                                                                                                          
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x'
permissions. It is recommended to double check and reset permissions for sensitive files and directories.                                                                
                                                                                                                                                                         
jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine                                                                               
$                                                                                                                                                                        
jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine
$ docker images
REPOSITORY                        TAG                 IMAGE ID            CREATED             SIZE
redmine_jedi                      latest              8f4e8d8db64a        45 seconds ago      408.9 MB
gcr.io/stacksmith-images/ubuntu   14.04-r8            65dfb2303799        4 weeks ago         227.2 MB

jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine
$ docker ps -a
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine
$ docker run -it --name redmine1 redmine_jedi:latest /bin/bash
standard_init_linux.go:175: exec user process caused "no such file or directory"

jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine
$

jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine
$ docker run -d --name redmine2 redmine_jedi:latest /bin/bash
fa1aae17653d8348680d72cc1be7690ffc8e98210fc8c74368637a333379c50e

jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine
$ docker ps -a
CONTAINER ID        IMAGE                 COMMAND                  CREATED             STATUS                      PORTS               NAMES
fa1aae17653d        redmine_jedi:latest   "/app-entrypoint.sh /"   13 seconds ago      Exited (1) 11 seconds ago                       redmine2

jedi_@JEDI_GPS Path\to\Dockerfile\bitnami-docker-redmine
$

And here is my docker-compose.yml

version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
  application:
    image: 'bitnami/redmine:latest'
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami/redmine'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local


Again, thank you very much for your help!

**Comment by sameersbn** [comment]
In the logs I noticed

```
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x'
permissions. It is recommended to double check and reset permissions for sensitive files and directories. 
```

This could be an issue. Instead of building the docker image locally, can you try using the prebuilt image from dockerhub?

**Comment by sameersbn** [comment]
In the logs I noticed

```
SECURITY WARNING: You are building a Docker image from Windows against a non-Windows Docker host. All files and directories added to build context will have '-rwxr-xr-x'
permissions. It is recommended to double check and reset permissions for sensitive files and directories. 
```

This could be an issue. Instead of building the docker image locally, can you try using the prebuilt image from dockerhub?

Everything else looks good to me and I would expect it work. Unfortunately I do not have Window 10 Pro with me to try out Docker for Windows.

**Comment by sameersbn** [comment]
I built the bitnami/redmine image on Windows (Docker Toolbox) and encountered the same issue. Looks like building linux based images on Windows is not advisable. You have the option of either using the prebuilt images from docker hub or performing your custom builds on a linux based docker host.

Let us know your feedback. Thanks.

**Comment by jedielson** [comment]
Hi

I've tried this

jedi_@JEDI_GPS Path\to\Docker
$  docker pull bitnami/redmine
Using default tag: latest
latest: Pulling from bitnami/redmine

56eb14001ceb: Pull complete
7ff49c327d83: Pull complete
6e532f87f96d: Pull complete
3ce63537e70c: Pull complete
df233bdf97ca: Pull complete
38563b1c0b05: Pull complete
525d5c144415: Pull complete
205a8fe3e347: Pull complete
ae3d32b0098d: Pull complete
c2b6b2c39173: Pull complete
aa00debcd63a: Pull complete
7116be6ced7e: Pull complete
97f82540805c: Pull complete
56b31b90fbbe: Pull complete
Digest: sha256:2c14a95b190f4d53cc0b4e44da1fb13825913df2964ccde6d38238f59fc0a9c3
Status: Downloaded newer image for bitnami/redmine:latest

jedi_@JEDI_GPS Path\to\Docker
$ docker network create redmine_network
2bc9896042878248fc1a7a8d55ba93fe4ae10a25da2f2c24078b56016130981c

jedi_@JEDI_GPS Path\to\Docker
$ docker run -d --name mariadb --net=redmine_network bitnami/mariadb
Unable to find image 'bitnami/mariadb:latest' locally
latest: Pulling from bitnami/mariadb

56eb14001ceb: Already exists
7ff49c327d83: Already exists
6e532f87f96d: Already exists
3ce63537e70c: Already exists
df233bdf97ca: Already exists
38563b1c0b05: Already exists
525d5c144415: Already exists
205a8fe3e347: Already exists
e2539acf32b2: Pull complete
b9aeaec803c0: Pull complete
Digest: sha256:15a03c1e9e0249a4392a27f02ca4246ccf112daa6a051906816bee1da182a88f
Status: Downloaded newer image for bitnami/mariadb:latest
685be6d197fefc3300a12ec117aed927333551dad5a9514daa7339579cd0eb78

jedi_@JEDI_GPS Path\to\Docker
$ docker run -d -p 3000:3000 --name redmine --net=redmine_network bitnami/redmine
8c0a2d9628cbf71e511aa5783d46775247ae8aa22d538c540a9eb2e9e07aa46f

jedi_@JEDI_GPS Path\to\Docker
$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                    NAMES
8c0a2d9628cb        bitnami/redmine     "/app-entrypoint.sh h"   35 seconds ago       Up 32 seconds       0.0.0.0:3000->3000/tcp   redmine
685be6d197fe        bitnami/mariadb     "/app-entrypoint.sh h"   About a minute ago   Up About a minute   3306/tcp                 mariadb


Apparently, the container is running.

The only issue is that At http://localhost:3000 redmine is not accessible.

Thanks for your help!

**Comment by sameersbn** [comment]
@jedielson according to https://docs.docker.com/docker-for-windows/ its supposed to work. can you validate the sample nginx container launch as listed in the linked page?

**Comment by jedielson** [comment]
It worked.

I don't did anything else, but it shoud me some minor issue.
I just reboot my SO.

Anyway, your product is amazing.
Thanks for your support!
