### ISSUE TITLE
Please add sqlite3 support to redmine image

### ISSUE THREAD

**Issue by datamove** [bitnami/bitnami-docker-redmine#25]
Dear developers
Do you mind to add sqlite3 support, for folks who don't want to run a separate database?
I have tried to to configure sqlite3 database adapter in database.yml, however the image lucks sqlite3 gem...
Thanks in advance!

**Comment by nomisbeme** [comment]
Thanks for the input, much appreciated. I'm curious why you prefer not to have a separate database container for your redmine data?

**Comment by datamove** [comment]
Hi, I installed Redmine for personal use on a home PC, so wanted to avoid managing extra CIs... On the other hand, I have also deployed a Bitnami owncloud container, so use of a DB (shared between app containers) is now more justified..
I filed this ticket thinking that it could be just one extra line in the Dockerfile along with other Ruby dependencies. Being new to Docker or Ruby, I don't know if it's easy/possible to install extra gems on an external docker volume for persistence, rather than tampering with the container or the image...
Anyway, Bitnami Redmine nad Owncloud containers are excellent, thanks!

**Comment by prydonius** [comment]
Hi @datamove, glad that Redmine and Owncloud are working out great for you! We discussed supporting other configurations, such as SQLite3 or PostgreSQL, but decided against it to make configuration and maintenance much simpler.

That being said, if it's something more people are interested, we would definitely like to revisit adding support for an SQLite3 configuration. I'm happy to keep this issue open to see if there are any thoughts around this.

**Comment by flah00** [comment]
I think that if this image is going to be the default, for helm charts, it should support the options available in the application. I've got an existing redmine install, which I'm trying to move to k8s. I'd love to use the chart, but I'm not too keen on moving my data from pg to maria.

**Comment by juan131** [comment]
@flah00 a workaround you can try is dumping your PG database and migrate it to a MySQL format using tools such as:
http://www.lightbox.ca/pg2mysql.php

Once you have your database with the new format, you can import it in the MariaDB database on k8s. 

> Note: That migration process does not always work so it might not be a solution for you. It is just a suggestion, do not perform it without a proper backup.

**Comment by flah00** [comment]
Thanks for the tip, @juan131. I considered it, but operationally, we've settled on postgres. Our team hasn't used mysql in nearly 10 years. That notwithstanding, once we get this issue resolved, I'd have convert the db back to postgres... Seems like a lot of hassle.

**Comment by prydonius** [comment]
Hey @flah00, thanks for the PR. It's important for us to reach feature parity with Docker official images - so I'm going to look into what it will take to add support for PostgreSQL/SQLite3 here.
