### ISSUE TITLE
Use Container Shell

### ISSUE THREAD

**Issue by jedielson** [bitnami/bitnami-docker-redmine#29]
Hi, 

How can I use the container shell (/bin/bash)

I've tried

docker start -ai, but it shows the Harpoon log, and I want to use shell...

Thanks for your help

**Comment by chipironcin** [comment]
Hi @jedielson 
Once you have launched the containers with `docker-compose` or one by one using `docker run`, you can enter a shell by executing:

    docker exec -it <container_id> bash

**Comment by jedielson** [comment]
Thanks!

It worked!

**Comment by prydonius** [comment]
Just to add, if you're using Docker Compose, you can run `docker-compose exec application bash`.
