### ISSUE TITLE
not have vim?

### ISSUE THREAD

**Issue by lifeblood** [bitnami/bitnami-docker-redmine#3]
not have vim?

**Comment by chipironcin** [comment]
Hi @lifeblood 
Our base image has been stripped down to ship minimum programs and libraries to make it as lighter as possible.
As Redmine files can be modified from outside the container mounting the volume, there is no need of a text editor inside it.
That's the reason why our images do not ship vim or emacs. Anyways you can install them by running the following commands inside the container:

    sudo apt-get update
    sudo apt-get install vim -y

Hope it helps.
If you have any other concern or feedback on our images, please let us know and we will be glad of hearing you :)

**Comment by lifeblood** [comment]
oh my god, i use yum install vim.

**Comment by chipironcin** [comment]
Our base image is based on Ubuntu.
Debian based distros (like Ubuntu) don't use the `yum` utility but `APT`. Yum is used in RedHat/Fedora/CentOS based distros. 
You can find more info about APT here:
https://en.wikipedia.org/wiki/Advanced_Packaging_Tool
