### ISSUE TITLE
MariaDB error on docker-compose up

### ISSUE THREAD

**Issue by stephane-r** [bitnami/bitnami-docker-redmine#83]
**Description**

After run my first **docker-compose up** (persisting application), i've an error with MariaDB :

```
(master) $> docker-compose up
Creating wwwredminelan_mariadb_1
Creating wwwredminelan_redmine_1
Attaching to wwwredminelan_mariadb_1, wwwredminelan_redmine_1
mariadb_1  | 
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | Send us your feedback at containers@bitnami.com
mariadb_1  | 
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redmine_1  | 
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | Send us your feedback at containers@bitnami.com
redmine_1  | 
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1  | mariadb INFO  ==> Initializing database...
mariadb_1  | Error executing 'postInstallation': 2017-03-17  6:24:54 140668763555712 [Note] /opt/bitnami/mariadb/sbin/mysqld (mysqld 10.1.21-MariaDB) starting as process 75 ...
mariadb_1  | 
redmine_1  | nami    INFO  Initializing redmine
wwwredminelan_mariadb_1 exited with code 1
redmine_1  | redmine INFO  Configuring Redmine database...
redmine_1  | mysqlCo INFO  Trying to connect to MySQL server
```

I've test to run my command with **sudo**, but no result. If i go on my **/opt/** folder, i've no 'bitnami' folder.

This error is on my production server. If i test my **docker-compose.yml** on local (Ubuntu too), it work.

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - './mariadb:/bitnami/mariadb'
  redmine:
    image: 'bitnami/redmine:latest'
    ports:
      - '3001:3000'
    volumes:
      - './redmine:/bitnami/redmine'
    depends_on:
      - mariadb
```

I've already 2 container started :

```
(master) $> docker ps
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS              PORTS                        NAMES
0d0cdcea52fa        abernix/meteord:base   "/bin/sh -c 'bash $ME"   12 days ago         Up 12 days          0.0.0.0:3000->80/tcp         app
5ea19eb12b15        mongo                  "/entrypoint.sh mongo"   7 months ago        Up 6 months         127.0.0.1:27017->27017/tcp   mongodb
```

**Steps to reproduce the issue:**

1. [First Step]
2. [Second Step]
3. [and so on...]

**Version**

- Output of `docker version`:

```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

- Output of `docker info`:

```
Containers: 4
 Running: 2
 Paused: 0
 Stopped: 2
Images: 9
Server Version: 1.12.1
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 77
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host overlay bridge
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-31-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.7 MiB
Name: stephane-richin
ID: PTYY:CIZ4:DKTH:OXIK:IA6T:4AOU:JRUG:5HNH:QXH5:CWM5:2BA3:JSEL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.11.2, build dfed245
docker-py version: 2.1.0
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

Anyone have idea ? ^^

Thank you !

**Comment by LeG3nDz** [comment]
Hi everybody,

I have just done new tests with sudo, root user and with your first example (without persisting application) and same result :/

**Comment by LeG3nDz** [comment]
No one has an idea ? :(

**Comment by jotadrilo** [comment]
Hi @LeG3nDz,

My understanding is that you are using docker on Windows, isn't it?
Could you try the same approach that I proposed in the WordPress issue with MariaDB?

1. Edit the `3/rootfs/app-entrypoint.sh` file
2. Add the following `chmod` command before the `exec tini -- "$@"` line:

```
chmod 0644 /opt/bitnami/mariadb/conf/my.cnf
exec tini -- "$@"
```

3. Rebuild the image with `docker build -t bitnami/mariadb:latest -t 3/Dockerfile 3`
4. Run the docker-compose command again

If this approach also solves your issue we will set the `my.cnf` permissions properly so other users won't face the same problem.

**Comment by LeG3nDz** [comment]
Yop @jotadrilo,

Not, i this case i use docker in my Linux server :) I've already try this solution, but no result :( (test too with chmod 777).

**Comment by sameersbn** [comment]
Hi @LeG3nDz. I am going to try out your docker-compose.yml spec on a ubuntu 14.04 machine.
Do you think thare are any particular steps you may have taken to cause this issue? How did you install docker? Are you using docker from the default ubuntu repos, or are you using the one provided by docker.com.

Also update docker to the latest version and retry?

**Comment by sameersbn** [comment]
Hi @LeG3nDz Upon closely looking at the output of `docker info` I noticed that the total available system memory of the host docker machine is 488.7 MiB. The available system memory will far lower.

The default MariaDB configuration requires above 128 MiB of available system memory and is probably the reason why the MariaDB server is unable to start.

You can try to customize the memory utilization of the MariaDB server by adding your custom configuration in a `conf/my_custom.cnf` file of the mariadb volume. But you will still have issues launching redmine on the server due to the low memory profile of the server.

I would suggest increasing the server instance size to have more than 1GiB of available system memory.

__please close the support request if this resolves the issue__

**Comment by sameersbn** [comment]
Closing this issue.. please re-open if problem persists.
