### ISSUE TITLE
Cannot new a custom field after installing the computed_custom_field plug-in.

### ISSUE THREAD

**Issue by yingsheng658** [bitnami/bitnami-docker-redmine#89]
Description:
After installing Redmine plugin as https://github.com/annikoff/redmine_plugin_computed_custom_field,
Will get internal error when we would like to new a custom field. 

Steps to reproduce the issue:
1.Download redmine_plugin_computed_custom_field.
2.Install plugin.
3.Migrate plugin.
4.Restart server.
5.Access the Redmine system.
6.New a custom field after installing the plug-in.

Describe the results you received:
Internal error when new a custom field after installing the plug-in.

Describe the results you expected:
Can new a custom field after installing the plug-in.

Version
Redmine version is v3.3.0-1.

Production log:
```
Started GET "/redmine/custom_fields/new?utf8=%E2%9C%93&type=IssueCustomField" for 127.0.0.1 at 2017-06-16 01:45:24 -0700
Processing by CustomFieldsController#new as HTML
  Parameters: {"utf8"=>"?", "type"=>"IssueCustomField"}
  Current user: user (id=1)
  Rendered custom_fields/formats/_regexp.html.erb (0.0ms)
  Rendered custom_fields/formats/_string.html.erb (0.0ms)
  Rendered plugins/computed_custom_field/app/views/hooks/_view_custom_fields_form_upper_box.html.erb (15.6ms)
  Rendered custom_fields/_form.html.erb (15.6ms)
  Rendered custom_fields/new.html.erb within layouts/admin (15.6ms)
Completed 500 Internal Server Error in 62ms (ActiveRecord: 46.8ms)

ActionView::Template::Error (undefined method `is_computed' for #<IssueCustomField:0xb23ba68>):
    1: <% if custom_field.new_record? || custom_field.is_computed? %>
    2:   <p><%= form.check_box :is_computed,
    3:                         data: { enables: '#custom_field_formula, #available_cfs' },
    4:                         disabled: !custom_field.new_record? %></p>
    5:   <p><%= form.text_area :formula, rows: 7 %></p>
  lib/redmine/views/labelled_form_builder.rb:34:in `check_box'
  plugins/computed_custom_field/app/views/hooks/_view_custom_fields_form_upper_box.html.erb:2:in `_plugins_computed_custom_field_app_views_hooks__view_custom_fields_form_upper_box_html_erb___558248688_63599544'
  lib/redmine/hook/view_listener.rb:59:in `block (2 levels) in render_on'
  lib/redmine/hook/view_listener.rb:57:in `map'
  lib/redmine/hook/view_listener.rb:57:in `block in render_on'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:96:in `call_hook'
  app/views/custom_fields/_form.html.erb:20:in `_app_views_custom_fields__form_html_erb__482887807_64258752'
  app/views/custom_fields/new.html.erb:4:in `block in _app_views_custom_fields_new_html_erb__350912484_64331700'
  app/helpers/application_helper.rb:1051:in `labelled_form_for'
  app/views/custom_fields/new.html.erb:3:in `_app_views_custom_fields_new_html_erb__350912484_64331700'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by andresbono** [comment]
Hi @yingsheng658,

We tried to reproduce the steps that you explained and we were able to install the plugin in the version that you are using (`3.3.0-r1`). We did the following inside the container:

- Download the latest version of the plugin in the right directory. Extract it:
```
cd /opt/bitnami/redmine/plugins
curl -Lo v1.0.5.tar.gz https://github.com/annikoff/redmine_plugin_computed_custom_field/archive/v1.0.5.tar.gz
tar zxf v1.0.5.tar.gz
```

- Run migrations
```
cd /opt/bitnami/redmine
RAILS_ENV=production bundle exec rake redmine:plugins:migrate
```

That's it. Then, you can go to your redmine administration pannel and create new custom fields:

![screen shot 2017-06-19 at 13 37 01](https://user-images.githubusercontent.com/1057973/27283419-7783bb1c-54f4-11e7-89c4-23f18b74b4c8.png)

Could you please try installing the plugin following this exactly steps on your container?

Best regards,
Andrés Bono

**Comment by yingsheng658** [comment]
Hi @andresbono ,

It's embarrassing that our Redmine system just set up under Windows server 2008 environment,
Could you have any suggestion for this case?Thanks in advanced.

**Comment by andresbono** [comment]
Hi @yingsheng658, are you using the Bitnami Redmine container in Docker for Windows or the [Bitnami Redmine Stack](https://bitnami.com/stack/redmine/installer#windows) in a Windows server?

Please, correct me if I'm not understanding something or I'm wrong!

**Comment by yingsheng658** [comment]
Hi @andresbono ,

We are using Bitnami Redmine Stack in the Windows server 2008.
Would you like to comment for this case?Thanks in advanced.

**Comment by carrodher** [comment]
Hi @yingsheng658,

Please note we are using this service only for questions and issues related to Bitnami Docker images. 

For issues related to our installers, cloud images, virtual machines, etc. please visit our [community support system](http://community.bitnami.com). Our support team will be glad to help you there.

In the [Redmine category](https://community.bitnami.com/c/redmine), there is a lot of post about this application, even a question similar to yours may have been answered before.

We regret the confusion, it is simply to keep our support channels orderly to provide a better help to the users.
