### ISSUE TITLE
Installation customization (plugins, templates, etc)

### ISSUE THREAD

**Issue by flah00** [bitnami/bitnami-docker-redmine#90]
**Description**

I have a highly specialized redmine installation, which I would like to migrate to kubernetes. It includes

* Gemfile.local
* config/application.rb
* various plugins
* various templates
* and a rails config/initializers/
* a patch, which I apply to a model

How can the image support user customization, or should the user build an image from the redmine image?

**Comment by sameersbn** [comment]
Hello @flah00, as you are configuring a highly customized redmine installation, I would suggest you extend the `bitnami/redmine` image and add the required configurations. For example, the following dockerfile extends the `bitnami/redmine:3.4.0-r0` image to add themes and plugins and executes `bundle install` to install gems required by them.

```dockerfile
FROM bitnami/redmine:3.4.0-r0

COPY plugins/ /opt/bitnami/redmine/plugins/
COPY themes/ /opt/bitnami/redmine/public/themes/

WORKDIR /opt/bitnami/redmine

RUN bundle config --local frozen 0 && \
    bundle install --without development test && \
    bundle config --local frozen 1
```

Similarly you should be able to customize the redmine installation in `/opt/bitnami/redmine`. 

To deploy the image on a kubernetes cluster, you can use the `stable/redmine` helm chart and specify your customized redmine image. f.e.

```bash
$ helm install stable/redmine --set image=flah00/redmine:x.x.x
```

Refer to https://github.com/kubernetes/charts/blob/master/stable/redmine/README.md for more information on the redmine chart.
