### ISSUE TITLE
Install ruby >= 2.2.2

### ISSUE THREAD

**Issue by flah00** [bitnami/bitnami-docker-redmine#92]
**Description**
I'm trying to build a new redmine, from bitnami/redmine:3.4.0-r0, with rails-observers-0.1.4. I'm unable to, because rails-observers-0.1.4 requires ruby >= 2.2.2. I'm not comfortable installing the previous version, as it's almost 4 years old.

All of this aside, ruby 2.1 support has [ceased](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/), as of April 2017.

**Steps to reproduce the issue:**

1. Add a Gemfile.local
    * `gem 'rails-observers'`
2. `bundle install --no-deployment`
    * `Gem::InstallError: rails-observers requires Ruby version >= 2.2.2.`

**Comment by sameersbn** [comment]
Thanks for the report @flah00. 
I've raised an internal request to look into upgrading the ruby version.

**Comment by sameersbn** [comment]
This is to inform you that we've updated the redmine image to use ruby-2.3 in release 3.4.1-r2.
Hope this helps. Thanks for choosing Bitnami Redmine.
