### ISSUE TITLE
chown: invalid spec: 'redmine:'

### ISSUE THREAD

**Issue by zoell** [bitnami/bitnami-docker-redmine#94]
**Description**

When starting the container I am getting an error when it is running the chown command.

**Steps to reproduce the issue:**

1. Run the container:
```
docker run \
    --cidfile="docker.pid" \
    -it \
    -p 80:3000 \
    --restart=always \
    --link redmine-mysql:mysql \
    --env='REDMINE_USERNAME=user' \
    --env='REDMINE_PASSWORD=pass' \
    --env='REDMINE_DB_MYSQL=redmine-mysql' \
    --env='REDMINE_DB_USERNAME=root' --env='REDMINE_DB_PASSWORD=rootpass' \
    -v /home/redmine/data:/bitnami \
    --name redmine \
    bitnami/redmine:latest
```

**Describe the results you received:**

```
Welcome to the Bitnami redmine container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
Send us your feedback at containers@bitnami.com

INFO  ==> Starting redmine...
chown: invalid spec: 'redmine:'
```

**Describe the results you expected:**

Container should start without error.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client version: 1.6.2
Client API version: 1.18
Go version (client): go1.2.1
Git commit (client): 7c8fca2
OS/Arch (client): linux/amd64
Server version: 1.6.2
Server API version: 1.18
Go version (server): go1.2.1
Git commit (server): 7c8fca2
OS/Arch (server): linux/amd64
```

- Output of `docker info`:

```
Containers: 2
Images: 45
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 49
 Dirperm1 Supported: false
Execution Driver: native-0.2
Kernel Version: 3.13.0-24-generic
Operating System: Ubuntu 14.04 LTS
CPUs: 1
Total Memory: 112.1 MiB
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
VPS

**Comment by jotadrilo** [comment]
Hi @zoell,

I see you are running an old version of docker. However, it could not be related to this issue.

I have some questions:
 - You are mounting `/home/redmine/data:/bitnami`, does `/home/redmine/data` already exist so you want to reuse it? If so, could you list its content?
 - Since you are running `docker run` directly, did you pull `bitnami/redmine:latest`?

The command you posted works in my local environment. For testing, I set up a `mariadb` container as follow:

```
> docker run --name redmine-mysql -e MARIADB_ROOT_PASSWORD=rootpass bitnami/mariadb:latest
```

**Comment by tompizmor** [comment]
Will continue at https://github.com/bitnami/bitnami-docker-redmine/issues/103
