### ISSUE TITLE
Customized image fails to nami initialize

### ISSUE THREAD

**Issue by flah00** [bitnami/bitnami-docker-redmine#95]
I created an image, from bitnami/redmine, and attempted to install it using the stable/redmine chart. Most everything went as planned, but the redmine pod keeps restarting. I'm able to reproduce this outside of k8s, when I run my [image](https://hub.docker.com/r/flah00/redmine) locally. I don't see how my changes are creating this error, but using the default image, with helm, I am able to login.

* [Gist](https://gist.github.com/flah00/7e51340c90baa81eb68283b43497615a)
* [Docker image](https://hub.docker.com/r/flah00/redmine/)
* [Helm wrapper](https://quay.io/application/adaptly/redmine-configmap)

**Steps to reproduce the issue:**

## Local

1. Copy [docker-compose.yaml](https://gist.github.com/flah00/7e51340c90baa81eb68283b43497615a#file-docker-compose-yml)
1. `docker-compose up`
2. `docker exec -ti NAME /bin/bash`
3. `NAMI_DEBUG="--log-level trace" /app-entrypoint.sh /run.sh`

## Kubernetes

1. Download [values.yaml](https://gist.github.com/flah00/7e51340c90baa81eb68283b43497615a#file-values-yaml)
1. `helm  registry install quay.io/adaptly/redmine-configmap:beta -f  values.yaml --name redmine`

**Describe the results you received:**

## Local

1. The first run yields an [error](https://gist.github.com/flah00/7e51340c90baa81eb68283b43497615a#file-run_1-txt): `nami    TRACE Error: Error executing 'postInstallation': User bn_redmine already exists`
1. All subsequent runs yield the [error](https://gist.github.com/flah00/7e51340c90baa81eb68283b43497615a#file-run_2-txt): `nami    TRACE Error: Error executing 'postInstallation': ELOOP: too many symbolic links encountered, lstat '/opt/bitnami/redmine/conf/configuration.yml'`

## Kubernetes

1. All runs yield the [error](https://gist.github.com/flah00/7e51340c90baa81eb68283b43497615a#file-kubernetes_run-txt): `nami    TRACE Error: Error executing 'postInstallation': File '/opt/bitnami/redmine/conf/database.yml' does not exists`
1. The conf directory, as viewed from nfs mount, is empty. The public directory is also empty (I've installed many themes there)
    * <pre>
        $ ls -l /efs/redmine/conf/
        total 0
        $ ls -l /efs/redmine/public/
        total 4
        drwxr-xr-x. 2 root root 6144 Sep 14 05:04 plugin_assets
</pre>

**Describe the results you expected:**

I would expect the ruby process to start up and serve requests.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
Client:
 Version:      17.06.1-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.1-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:54:55 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

- Output of `docker info`:

```
Containers: 4
 Running: 3
 Paused: 0
 Stopped: 1
Images: 160
Server Version: 17.06.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 136
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: moby
ID: AH5Q:U6DO:6QVV:MBQG:ODRL:6X5M:TVMR:4U2E:3I7E:F5JP:JEG5:GFZL
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 45
 Goroutines: 55
 System Time: 2017-09-14T04:15:38.571737554Z
 EventsListeners: 1
No Proxy: *.local, 169.254/16
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- Output of `docker-compose version` (if applicable):

```
docker-compose version 1.14.0, build c7bdf9e
docker-py version: 2.3.0
CPython version: 2.7.12
OpenSSL version: OpenSSL 1.0.2j  26 Sep 2016
```

**Comment by prydonius** [comment]
@flah00 thanks for the detailed report, I'll take a look and see what I can find

**Comment by prydonius** [comment]
When I ran this, I got the following error:

```
$ docker exec -ti flah00_redmine_1 bash
root@da6d7ab7a70a:/# NAMI_DEBUG="--log-level trace" /app-entrypoint.sh /run.sh
app-entrypoint.sh 11:01:36.59
app-entrypoint.sh 11:01:36.59 Welcome to the Bitnami redmine container
app-entrypoint.sh 11:01:36.60 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
app-entrypoint.sh 11:01:36.60 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
app-entrypoint.sh 11:01:36.60 Send us your feedback at containers@bitnami.com
app-entrypoint.sh 11:01:36.60
nami    INFO  Initializing redmine
redmine DEBUG Creating Redmine System User...
redmine DEBUG ==> Detected PostgreSQL database
redmine INFO  Configuring Redmine database...
postgre INFO  Trying to connect to PostgreSQL server
postgre INFO  Found PostgreSQL server listening at postgresql:5432
postgre TRACE [canConnect] Testing connection with 'postgres' user
postgre TRACE [showDatabases] Getting databases for 'postgres' user
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cSELECT datname FROM pg_database;
postgre TRACE [showDatabases] Databases: " postgres\n template1\n template0\n\n"
postgre TRACE [canConnect] Connection with 'postgres' user is successful
postgre INFO  PostgreSQL server listening and working at postgresql:5432
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-c\list
redmine DEBUG Creating database 'bitnami_redmine'                for 'bn_redmine' with 'x10IfWAnpk'
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cSELECT 1 FROM pg_database WHERE datname='bitnami_redmine'
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cCREATE DATABASE bitnami_redmine
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cSELECT 1 FROM pg_roles WHERE rolname='bn_redmine'
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dpostgres,-Upostgres,-cCREATE USER "bn_redmine" PASSWORD 'x10IfWAnpk'
postgre TRACE [execute] Executing psql with parameters -t,-p5432,-hpostgresql,-dbitnami_redmine,-Upostgres,-cGRANT ALL PRIVILEGES ON DATABASE bitnami_redmine TO bn_redmine
Error executing 'postInstallation': File /opt/bitnami/redmine/conf/database.yml did not match any of the provided substitutions
nami    TRACE Error: Error executing 'postInstallation': File /opt/bitnami/redmine/conf/database.yml did not match any of the provided substitutions
    at /opt/bitnami/nami/node_modules/nami-utils/lib/file/substitute.js:47:13
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
    at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
    at _massFileSubstitute (/opt/bitnami/nami/node_modules/nami-utils/lib/file/substitute.js:39:5)
    at Object.substitute (/opt/bitnami/nami/node_modules/nami-utils/lib/file/substitute.js:180:5)
    at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)
    at Service.$app.postInstallation (/root/.nami/components/com.bitnami.redmine/main.js:47:11)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
```

It looks like you're changing the database.yml in `/opt/bitnami/redmine/config` which is causing this failure.

```
$ docker run --rm -ti -e DISABLE_WELCOME_MESSAGE=1 flah00/redmine:3.4 cat /opt/bitnami/redmine/config/database.yml
test:
  adapter: postgresql
```

```
docker run --rm -ti -e DISABLE_WELCOME_MESSAGE=1 bitnami/redmine:3 cat /opt/bitnami/redmine/config/database.yml
# Default setup is given for MySQL with ruby1.9.
# Examples for PostgreSQL, SQLite3 and SQL Server can be found at the end.
# Line indentation must be 2 spaces (no tabs).

production:
  adapter: mysql2
  database: redmine
  host: localhost
  username: root
  password: ""
  encoding: utf8

development:
  adapter: mysql2
  database: redmine_development
  host: localhost
  username: root
  password: ""
  encoding: utf8

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: redmine_test
  host: localhost
  username: root
  password: ""
  encoding: utf8

# PostgreSQL configuration example
#production:
#  adapter: postgresql
#  database: redmine
#  host: localhost
#  username: postgres
#  password: "postgres"

# SQLite3 configuration example
#production:
#  adapter: sqlite3
#  database: db/redmine.sqlite3

# SQL Server configuration example
#production:
#  adapter: sqlserver
#  database: redmine
#  host: localhost
#  username: jenkins
#  password: jenkins
```

I'm assuming you're changing this when copying in `redmine-aptly`. Is there a particular reason for that?

I'm sure this is just scratching the surface of this issue, I'll take a look at the nami logic to see what the module expects.

**Comment by flah00** [comment]
Really appreciate your rapid reply!

Good catch. I think I had to modify the database.yml, in my previous build process, because of gem issues. If I recall correctly, my system didn't have mysql on it, and the default database.yml somehow lead bundle to install mysql by default... So I yanked all mysql refs out.

I'll remove my database.yml and see how it goes.

It seems like a full re-write of config files might be a safer route, for configuring the system. Personally, I prefer the `DATABASE_URL` route. It removes concerns about formatting and what not. And you can easily inject additional config options, via query params, without fussing with yaml white space.

**Comment by prydonius** [comment]
I agree about rewriting, although that does remove the potential to configure other options in database.yml.

I too prefer `DATABASE_URL` and we do this in our Rails image, but note that it isn't respected for test and other environments (https://github.com/bitnami/bitnami-docker-rails/issues/61).

Let me know how that goes, I assume we are changing the adapter in the default database.yml when Postgres is used.

**Comment by flah00** [comment]
I replaced mysql all mentions, in the database.yml, with postgres and I can build, install, and almost bootstrap my charted pod, in kubernetes. Thanks for the pointer!

## Kubernetes pod log

```
nami    INFO  Initializing redmine
redmine DEBUG Creating Redmine System User...
redmine DEBUG ==> Detected PostgreSQL database
redmine INFO  Redmine has been already initialized, restoring...
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/conf to /opt/bitnami/redmine/conf
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/public/plugin_assets to /opt/bitnami/redmine/public/plugin_assets
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/plugins to /opt/bitnami/redmine/plugins
redmine TRACE [restorePersistedData] Restoring /bitnami/redmine/files to /opt/bitnami/redmine/files
postgre INFO  Trying to connect to PostgreSQL server
```

It seems that since I have defined a PVC which mounts to `/bitnami/redmine`, `isInitialized` (`/root/.nami/components/com.bitnami.redmine/lib/volume.js#212`) returns `true`. This prevents the substitution code from running (`/root/.nami/components/com.bitnami.redmine/main.js#93`). 

Which repo stores the files in `/root/.nami/components/com.bitnami.redmine`? Seems odd that they aren't part of this repo.

ps - Environment variables that only work in certain environments make me very sad.

**Comment by flah00** [comment]
I was going to manually edit the `conf/database.yml` file, but I've run into another issue... The `REDMINE_DB_PASSWORD` will not allow me to login. I also tried the `POSTGRES_PASSWORD`, defined in the postgres container. It seems the redmine database does not exist either.

## From the postgres container

```
root@redmine-postgresql-786238283-4j6zf:/# psql -l
                                 List of databases
   Name    |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges
-----------+----------+----------+------------+------------+-----------------------
 postgres  | postgres | UTF8     | en_US.utf8 | en_US.utf8 |
 template0 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
 template1 | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
           |          |          |            |            | postgres=CTc/postgres
(3 rows)
```

**Comment by prydonius** [comment]
It sounds like your PVC has been "initialized" but with a failing state, you need to exec into your pod and clear the volume (including dot files, I think it looks for something like `.initialized`). Once you've done that, delete the pod and it'll restart and initialize as if it's the first time. You may need to keep doing this as we debug this, so it might be better to temporarily use an emptyDir.

**Comment by iWangJiaxiang** [comment]
> It sounds like your PVC has been "initialized" but with a failing state, you need to exec into your pod and clear the volume (including dot files, I think it looks for something like `.initialized`). Once you've done that, delete the pod and it'll restart and initialize as if it's the first time. You may need to keep doing this as we debug this, so it might be better to temporarily use an emptyDir.

You saved me! I tried to reinstall redmine but it said restoring.... I didn't realized there were hidden files.
