### ISSUE TITLE
Redmine Redmineup  Agile plugin installation fails

### ISSUE THREAD

**Issue by alevashov** [bitnami/bitnami-docker-redmine#97]
**Description**

Can't install Redmineup Agile (Light version) plugin for Redmine

I have followed the instructions at https://docs.bitnami.com/bch/apps/redmine/#install_plugins

1. Copied plugin files to plugins folder and unzipped them
2. Remove the ".zip" file:
3. Returned to htdocs directory and tried to install required gems:
cd /opt/bitnami/apps/redmine/htdocs/
bundle install --without development test postgresql sqlite --no-deployment

**Describe the results you received:**

Got error as below:

bitnami@ip-10-41-236-234:/opt/bitnami/apps/redmine/htdocs$ bundle install --without development test postgresql sqlite --no-deployment 
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x64-mingw32, x86-mswin32. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x64-mingw32 x86-mswin32`. 
Fetching gem metadata from https://rubygems.org/.......... 
Fetching version metadata from https://rubygems.org/.. 
Fetching dependency metadata from https://rubygems.org/. 
Resolving dependencies..... 
Using rake 12.3.0 
Using i18n 0.7.0 
Using minitest 5.11.1 
Using thread_safe 0.3.6 
Using builder 3.2.3 
Using erubis 2.7.0 
Using mini_portile2 2.3.0 
Using crass 1.0.3 
Using rack 1.6.8 
Using mime-types-data 3.2016.0521 
Using arel 6.0.4 
Using public_suffix 3.0.1 
Using bundler 1.14.6 
Using coderay 1.1.2 
Using concurrent-ruby 1.0.5 
Using htmlentities 4.3.4 
Using thor 0.20.0 
Using liquid 2.6.3 
Using mimemagic 0.3.2 
Installing mysql2 0.4.10 with native extensions 
Using net-ldap 0.12.1 
Using ruby-openid 2.3.0 
Using rbpdf-font 1.19.1 
Using redcarpet 3.4.0 
Using request_store 1.0.5 
Installing rmagick 2.16.0 with native extensions 
Using tzinfo 1.2.4 
Using nokogiri 1.8.1 
Using rack-test 0.6.3 
Using mime-types 3.1 
Using addressable 2.5.2 
Using sprockets 3.7.1 
Using redmine_crm 0.0.34 
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory: 
/tmp/bundler20180125-26418-17tzc4lmysql2-0.4.10/gems/mysql2-0.4.10/ext/mysql2 
/opt/bitnami/ruby/bin/ruby -r ./siteconf20180125-26418-1hgh6fq.rb extconf.rb 
checking for rb_absint_size()... yes 
checking for rb_absint_singlebit_p()... yes 
checking for ruby/thread.h... yes 
checking for rb_thread_call_without_gvl() in ruby/thread.h... yes 
checking for rb_thread_blocking_region()... no 
checking for rb_wait_for_single_fd()... yes 
checking for rb_hash_dup()... yes 
checking for rb_intern3()... yes 
checking for rb_big_cmp()... yes 
----- 
Using mysql_config at /opt/bitnami/mysql/bin/mysql_config 
----- 
checking for mysql.h... yes 
checking for errmsg.h... yes 
checking for SSL_MODE_DISABLED in mysql.h... no 
checking for MYSQL_OPT_SSL_ENFORCE in mysql.h... no 
checking for MYSQL.net.vio in mysql.h... yes 
checking for MYSQL.net.pvio in mysql.h... no 
checking for MYSQL_ENABLE_CLEARTEXT_PLUGIN in mysql.h... yes 
----- 
Setting libpath to /opt/bitnami/mysql/lib 
----- 
creating Makefile

current directory: 
/tmp/bundler20180125-26418-17tzc4lmysql2-0.4.10/gems/mysql2-0.4.10/ext/mysql2 
make "DESTDIR=" clean

current directory: 
/tmp/bundler20180125-26418-17tzc4lmysql2-0.4.10/gems/mysql2-0.4.10/ext/mysql2 
make "DESTDIR=" 
compiling infile.c 
compiling client.c 
compiling statement.c 
compiling mysql2_ext.c 
compiling result.c 
result.c: In function ‘rb_mysql_result_alloc_result_buffers’: 
result.c:326:40: warning: assignment from incompatible pointer type 
wrapper->result_buffers[i].is_null = &wrapper->is_null[i]; 
^ 
result.c:328:40: warning: assignment from incompatible pointer type 
wrapper->result_buffers[i].error = &wrapper->error[i]; 
^ 
result.c: At top level: 
cc1: warning: unrecognized command line option "-Wno-used-but-marked-unused" 
cc1: warning: unrecognized command line option "-Wno-static-in-inline" 
cc1: warning: unrecognized command line option "-Wno-reserved-id-macro" 
cc1: warning: unrecognized command line option 
"-Wno-missing-variable-declarations" 
cc1: warning: unrecognized command line option 
"-Wno-documentation-unknown-command" 
cc1: warning: unrecognized command line option "-Wno-disabled-macro-expansion" 
cc1: warning: unrecognized command line option "-Wno-covered-switch-default" 
cc1: warning: unrecognized command line option "-Wno-conditional-uninitialized" 
linking shared-object mysql2/mysql2.so

current directory: 
/tmp/bundler20180125-26418-17tzc4lmysql2-0.4.10/gems/mysql2-0.4.10/ext/mysql2 
make "DESTDIR=" install 
/bin/install -c -m 0755 mysql2.so ./.gem.20180125-26418-9usfme/mysql2 
make: /bin/install: Command not found 
Makefile:186: recipe for target 'install-so' failed 
make: *** [install-so] Error 127

make install failed, exit code 2

Gem files will remain installed in 
/tmp/bundler20180125-26418-17tzc4lmysql2-0.4.10/gems/mysql2-0.4.10 for 
inspection. 
Results logged to 
/tmp/bundler20180125-26418-17tzc4lmysql2-0.4.10/extensions/x86_64-linux/2.3.0-static/mysql2-0.4.10/gem_make.out

An error occurred while installing mysql2 (0.4.10), and Bundler cannot 
continue. 
Make sure that `gem install mysql2 -v '0.4.10'` succeeds before bundling.

**Describe the results you expected:**

Success, confirmation that the gem is installed

**Additional information you deem important (e.g. issue happens only occasionally):**

After that I have tried to restart the instance and ended up with Passenger error

We're sorry, but something went wrong.
The issue has been logged for investigation. Please try again later.

Error:
Web application could not be started
Error ID:
5e5de6c2
Details:
Web application could not be started by the Phusion Passenger application server.

Please read the Passenger log file (search for the Error ID) to find the details of the error.

You can also get a detailed report to appear directly on this page, but for security reasons it is only provided if Phusion Passenger is run with environment set to development and/or with the friendly error pages option set to on.

For more information about configuring environment and friendly error pages, see:

Nginx integration mode
Apache integration mode
Standalone mode
**Version**

- Output of `docker version`:

```
Redmine 3.4.4-1
```

- Output of `docker info`:

```
bitnami@ip-10-41-236-234:~$ docker info
-bash: docker: command not found

```

- Output of `docker-compose version` (if applicable):

```
docker-compose version
-bash: docker-compose: command not found

```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**
AWS

**Comment by javsalgar** [comment]
Hi,

It looks to me that you are not using the Bitnami Redmine container but the Bitnami Redmine installer or cloud Image. If that is the case, could you please open the ticket in community.bitnami.com? Thanks
