### ISSUE TITLE
redmine_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redmine'

### ISSUE THREAD

**Issue by rockycao** [bitnami/bitnami-docker-redmine#98]
When docker-compose up the redmine container , I'm presented with this error:

1. [First Step]
centos 7.4
git clone https://github.com/bitnami/bitnami-docker-redmine.git
2. [Second Step]
cd 
docker-compose up
error：

Attaching to bitnamidockerredmine_mariadb_1, bitnamidockerredmine_redmine_1
redmine_1  |
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | Send us your feedback at containers@bitnami.com
redmine_1  |
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | Send us your feedback at containers@bitnami.com
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO   Installation parameters for mariadb:
mariadb_1  | mariadb INFO     Persisted data and properties have been restored.
mariadb_1  | mariadb INFO     Any input specified will not take effect.
mariadb_1  | mariadb INFO   This installation requires no credentials.
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO
mariadb_1  | nami    INFO  mariadb successfully initialized
mariadb_1  | INFO  ==> Starting mariadb...
mariadb_1  | INFO  ==> Starting mysqld_safe...
mariadb_1  | 180126 12:44:35 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 180126 12:44:35 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | redmine INFO  Configuring Redmine database...
redmine_1  | mysql-c INFO  Trying to connect to MySQL server
redmine_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
redmine_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
redmine_1  | redmine INFO  Preparing Redmine environment...
redmine_1  | redmine INFO  Migrating database...
redmine_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redmine'

**Version**

- Output of `docker version`:

Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Sep  7 18:00:07 2017
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-48.git0fdc778.el7.centos.x86_64
 Go version:      go1.8.3
 Git commit:      0fdc778/1.12.6
 Built:           Thu Sep  7 18:00:07 2017
 OS/Arch:         linux/amd64

- Output of `docker info`:

Containers: 8
 Running: 5
 Paused: 0
 Stopped: 3
Images: 33
Server Version: 1.12.6
Storage Driver: devicemapper
 Pool Name: docker-253:0-166649-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 5.643 GB
 Data Space Total: 107.4 GB
 Data Space Available: 29.67 GB
 Metadata Space Used: 8.651 MB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.139 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: true
 Deferred Deletion Enabled: true
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.140-RHEL7 (2017-05-03)
Logging Driver: journald
Cgroup Driver: systemd
Plugins:
 Volume: local
 Network: host overlay bridge null
Swarm: inactive
Runtimes: docker-runc runc
Default Runtime: docker-runc
Security Options: seccomp selinux
Kernel Version: 3.10.0-693.2.2.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
Number of Docker Hooks: 3
CPUs: 4
Total Memory: 11.58 GiB
Name: localhost.localdomain
ID: 76X4:D5YD:ISHQ:7PQD:R27B:WPVC:4WNM:N5LB:FCLS:YU3X:SRZG:WT4V
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Insecure Registries:
 127.0.0.0/8
Registries: docker.io (secure)

- Output of `docker-compose version` (if applicable):

docker-compose version 1.12.0, build b31ff33
docker-py version: 2.2.1
CPython version: 2.7.13
OpenSSL version: OpenSSL 1.0.1t  3 May 2016

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

CentOS Linux release 7.4.1708 (Core)

        Product Name: VMware Virtual Platform
        Product Name: 440BX Desktop Reference Platform

**Comment by juan131** [comment]
Hi @rockycao I was unable to reproduce the issue. 

It seems that for some reason the user running the Redmine Nami module doesn't have enough permissions to create new directories within the Docker image... 

@tompizmor @sameersbn do you have any idea why this could be happening?

**Comment by tompizmor** [comment]
HI @rockycao,

Per the following part of the output, it seems that you already have persisted data in the mariadb volume and probably the same for the redmine one.

```
mariadb_1 | mariadb INFO Installation parameters for mariadb:
mariadb_1 | mariadb INFO Persisted data and properties have been restored.
mariadb_1 | mariadb INFO Any input specified will not take effect.
mariadb_1 | mariadb INFO This installation requires no credentials.
```

If you are not worried about losing the data that you may have in the volume please run these commands to start from scratch:

```
$ docker-compose down -v
$ docker-compose up
```

If you have any error please paste here the output.

**Comment by rockycao** [comment]
[root@localhost bitnami-docker-redmine]# **docker-compose down -v**
Removing bitnamidockerredmine_redmine_1 ... done
Removing bitnamidockerredmine_mariadb_1 ... done
Removing network bitnamidockerredmine_default
Removing volume bitnamidockerredmine_redmine_data
Removing volume bitnamidockerredmine_mariadb_data
[root@localhost bitnami-docker-redmine]# **docker-compose up**
Creating network "bitnamidockerredmine_default" with the default driver
Creating volume "bitnamidockerredmine_redmine_data" with local driver
Creating volume "bitnamidockerredmine_mariadb_data" with local driver
Creating bitnamidockerredmine_mariadb_1
Creating bitnamidockerredmine_redmine_1
Attaching to bitnamidockerredmine_mariadb_1, bitnamidockerredmine_redmine_1
mariadb_1  |
mariadb_1  | Welcome to the Bitnami mariadb container
mariadb_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1  | Send us your feedback at containers@bitnami.com
mariadb_1  |
mariadb_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
redmine_1  |
redmine_1  | Welcome to the Bitnami redmine container
redmine_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redmine
redmine_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redmine/issues
redmine_1  | Send us your feedback at containers@bitnami.com
redmine_1  |
mariadb_1  | nami    INFO  Initializing mariadb
mariadb_1  | mariadb INFO  ==> Cleaning data dir...
mariadb_1  | mariadb INFO  ==> Configuring permissions...
mariadb_1  | mariadb INFO  ==> Validating inputs...
mariadb_1  | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1  | mariadb INFO  ==> Initializing database...
redmine_1  | nami    INFO  Initializing redmine
redmine_1  | redmine INFO  Configuring Redmine database...
redmine_1  | mysql-c INFO  Trying to connect to MySQL server
mariadb_1  | mariadb INFO  ==> Creating 'root' user with unrestricted access...
mariadb_1  | mariadb INFO  ==> Enabling remote connections...
mariadb_1  | mariadb INFO
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO   Installation parameters for mariadb:
mariadb_1  | mariadb INFO     Root User: root
mariadb_1  | mariadb INFO     Root Password: Not set during installation
mariadb_1  | mariadb INFO   (Passwords are not shown for security reasons)
mariadb_1  | mariadb INFO  ########################################################################
mariadb_1  | mariadb INFO
mariadb_1  | nami    INFO  mariadb successfully initialized
mariadb_1  | INFO  ==> Starting mariadb...
mariadb_1  | INFO  ==> Starting mysqld_safe...
mariadb_1  | 180131 00:54:56 mysqld_safe Logging to '/opt/bitnami/mariadb/logs/mysqld.log'.
mariadb_1  | 180131 00:54:56 mysqld_safe Starting mysqld daemon with databases from /opt/bitnami/mariadb/data
redmine_1  | mysql-c INFO  Found MySQL server listening at mariadb:3306
redmine_1  | mysql-c INFO  MySQL server listening and working at mariadb:3306
redmine_1  | redmine INFO  Preparing Redmine environment...
redmine_1  | redmine INFO  Migrating database...
redmine_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redmine'
bitnamidockerredmine_redmine_1 exited with code 1

**Comment by rockycao** [comment]
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,redmine:plugins:migrate
redmine_1  | ruby    TRACE [runProgram] Executing internal command: /opt/bitnami/ruby/bin/ruby ["/opt/bitnami/ruby/bin/bundle","exec","rake","redmine:plugins:migrate"]
redmine_1  | ruby    TRACE [runProgram] RESULT: {"code":0,"stderr":"","stdout":""}
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,generate_secret_token
redmine_1  | ruby    TRACE [runProgram] Executing internal command: /opt/bitnami/ruby/bin/ruby ["/opt/bitnami/ruby/bin/bundle","exec","rake","generate_secret_token"]
redmine_1  | ruby    TRACE [runProgram] RESULT: {"code":0,"stderr":"","stdout":""}
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [normalize] File normalization: bin -> /opt/bitnami/ruby/bin
redmine_1  | ruby    TRACE [runProgram] Executing: /opt/bitnami/ruby/bin/ruby /opt/bitnami/ruby/bin/bundle,exec,rake,redmine:load_default_data
redmine_1  | ruby    TRACE [runProgram] Executing internal command: /opt/bitnami/ruby/bin/ruby ["/opt/bitnami/ruby/bin/bundle","exec","rake","redmine:load_default_data"]
redmine_1  | ruby    TRACE [runProgram] RESULT: {"code":0,"stderr":"","stdout":"Default configuration data loaded.\n"}
redmine_1  | redmine TRACE [exists] File normalization: /opt/bitnami/redmine/conf -> /opt/bitnami/redmine/conf
redmine_1  | redmine TRACE [prepareDataToPersist] Preparing /opt/bitnami/redmine/conf to persist in /bitnami/redmine/conf
redmine_1  | redmine TRACE [dirname] File normalization: /opt/bitnami/redmine/conf -> /opt/bitnami/redmine/conf
redmine_1  | redmine TRACE [dirname] File normalization: /bitnami/redmine/conf -> /bitnami/redmine/conf
redmine_1  | redmine TRACE [isDirectory] File normalization: /opt/bitnami/redmine/conf -> /opt/bitnami/redmine/conf
redmine_1  | redmine TRACE [mkdir] File normalization: /bitnami/redmine/conf -> /bitnami/redmine/conf
redmine_1  | nami    TRACE Error: Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/redmine'
redmine_1  |     at Error (native)
redmine_1  |     at Object.fs.mkdirSync (fs.js:916:18)
redmine_1  |     at mkdirsSync (/opt/bitnami/nami/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:29:9)
redmine_1  |     at Object.mkdirsSync (/opt/bitnami/nami/node_modules/fs-extra/lib/mkdirs/mkdirs-sync.js:35:16)
redmine_1  |     at Object.mkdir (/opt/bitnami/nami/node_modules/nami-utils/lib/file/mkdir.js:28:8)
redmine_1  |     at Object.wrappedFn (/opt/bitnami/nami/node_modules/nami-utils/lib/function-wrapping.js:191:17)
redmine_1  |     at _recursiveMove (/root/.nami/components/com.bitnami.redmine/lib/volume.js:37:13)
redmine_1  |     at _.each (/root/.nami/components/com.bitnami.redmine/lib/volume.js:131:7)
redmine_1  |     at ot (/opt/bitnami/nami/node_modules/lodash/index.js:12:507)
redmine_1  |     at Function.<anonymous> (/opt/bitnami/nami/node_modules/lodash/index.js:33:421)
bitnamidockerredmine_redmine_1 exited with code 1

**Comment by rockycao** [comment]
[root@localhost bitnami-docker-redmine]# vi docker-compose.yml
[root@localhost bitnami-docker-redmine]# docker-compose down -v
Removing network bitnamidockerredmine_default
WARNING: Network bitnamidockerredmine_default not found.
Removing volume bitnamidockerredmine_redmine_data
WARNING: Volume bitnamidockerredmine_redmine_data not found.
Removing volume bitnamidockerredmine_mariadb_data
WARNING: Volume bitnamidockerredmine_mariadb_data not found.
[root@localhost bitnami-docker-redmine]# docker-compose up

**Comment by tompizmor** [comment]
Hello @rockycao,

Where you able to run the WordPress container?

I am sorry but I am unable to reproduce the issue on a similar environment (Centos 7.4 with `devicemapper` as storage driver)

Your docker version is a bit outdated. I am not sure if that could be related. Would be possible for you to upgrade to a recent version?

**Comment by rockycao** [comment]
[root@localhost wordpress]# curl -LO https://raw.githubusercontent.com/bitnami/bitnami-docker-wordpress/master/docker-compose.yml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   752  100   752    0     0    657      0  0:00:01  0:00:01 --:--:--   657
[root@localhost wordpress]# docker-compose up
Creating network "wordpress_default" with the default driver
Creating volume "wordpress_wordpress_data" with local driver
Creating volume "wordpress_mariadb_data" with local driver
Creating wordpress_mariadb_1
Creating wordpress_wordpress_1
Attaching to wordpress_mariadb_1, wordpress_wordpress_1
mariadb_1    |
mariadb_1    | Welcome to the Bitnami mariadb container
mariadb_1    | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-mariadb
mariadb_1    | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-mariadb/issues
mariadb_1    | Send us your feedback at containers@bitnami.com
mariadb_1    |
mariadb_1    | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
wordpress_1  |
wordpress_1  | Welcome to the Bitnami wordpress container
wordpress_1  | Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-wordpress
wordpress_1  | Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-wordpress/issues
wordpress_1  | Send us your feedback at containers@bitnami.com
wordpress_1  |
wordpress_1  | WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
mariadb_1    | nami    INFO  Initializing mariadb
mariadb_1    | mariadb INFO  ==> Cleaning data dir...
mariadb_1    | mariadb INFO  ==> Configuring permissions...
mariadb_1    | mariadb INFO  ==> Validating inputs...
mariadb_1    | mariadb WARN  Allowing the "rootPassword" input to be empty
mariadb_1    | mariadb WARN  Allowing the "password" input to be empty
mariadb_1    | mariadb INFO  ==> Initializing database...
wordpress_1  | nami    INFO  Initializing apache
wordpress_1  | apache  INFO  ==> Patching httpoxy...
wordpress_1  | Error executing 'postInstallation': EACCES: permission denied, mkdir '/bitnami/apache'
wordpress_wordpress_1 exited with code 1

**Comment by tompizmor** [comment]
I would say there is something going on in your Centos environment. 

* Could you check if SELinux is enabled?

```
$ sestatus
```

* If it is enabled, can you check if you are getting denials?

```
$ sudo ausearch -m avc
```

* As the issue seems to be creating the persisted directory in the host machine (Centos), you can also try starting the container without any volume. 

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes'
  redmine:
    image: 'bitnami/redmine:3.4.4-r0'
    environment:
      - NAMI_LOG_LEVEL=trace8
    ports:
      - '80:3000'
    depends_on:
      - mariadb
```

Please try the above things and paste the output of each command.

**Comment by tompizmor** [comment]
Hi @rockycao,

There was a typo in the last docker-compose file and because of that Redmine was not able to connect to the database. Sorry about that. Can you try this one? 

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  redmine:
    image: 'bitnami/redmine:3.4.4-r0'
    environment:
      - NAMI_LOG_LEVEL=trace8
    ports:
      - '80:3000'
    depends_on:
      - mariadb
```

Also, it seems SELinux is blocking some actions from the container so I would say this is the origin of the issues that you found. 

```
fsgid=0 tty=(none) ses=4294967295 comm="node" exe="/opt/bitnami/nami/runtime/node" subj=system_u:system_r:svirt_lxc_net_t:s0:c674,c973 key=(null)
type=AVC msg=audit(1517887687.102:23869): avc: denied { create } for pid=30884 comm="node" name="apache" scontext=system_u:system_r:svirt_lxc_net_t:s0:c674,c973 tcontext=system_u:object_r:container_var_lib_t:s0 tclass=dir
```

As commented in [this similar issue](https://github.com/tomav/docker-mailserver/issues/753) it seems the `:z` flag for volumes can help. If you want to preserve the data, try with the below docker-compose.

```
version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_data:/bitnami:z'
  redmine:
    image: 'bitnami/redmine:3.4.4-r0'
    environment:
      - NAMI_LOG_LEVEL=trace8
    ports:
      - '80:3000'
    volumes:
      - 'redmine_data:/bitnami:z'
    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  redmine_data:
    driver: local
```

**Comment by rockycao** [comment]
Thanks to tompizmor 's help. :z flag  resolve the problem.

**Comment by tompizmor** [comment]
Thank you for confirming that it worked!
