### ISSUE TITLE
docker run after 3~10sec wait, suddenly container shutdown

### ISSUE THREAD

**Issue by pigbean** [bitnami/bitnami-docker-redmine#99]
**Description**

**Steps to reproduce the issue:**
1. Synology Download Package Cneter login
2. docker image download (image : bitnami/redmine:latest)
3. download image use, docker run
4. 3~10 sec wait, Unexpectedly Error & docker shutdown

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

docker version : 17.05.0-0367
Synology DSM version : DSM 6.1.4-15217 update 5

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```
![image](https://user-images.githubusercontent.com/27951070/37100837-5779ed96-2267-11e8-86c5-0d57b989fbcb.png)

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by dbarranco** [comment]
Hi @pigbean 

Could you please point us where are you downloading that software to run the containers? Would be pretty useful to have a proper environment to test the container, as we're unable to reproduce this issue.

Also, could you please run the container but adding the environment variable?
`NAMI_LOG_LEVEL=trace` with that, we will be able to see more details about which is the instruction the container is executing before crashing.

Kind regards!
